[2024-05-01T17:36:33.774+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T17:36:33.951+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T12:35:18.514753+00:00 [queued]>
[2024-05-01T17:36:33.985+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T12:35:18.514753+00:00 [queued]>
[2024-05-01T17:36:33.987+0300] {taskinstance.py:2303} INFO - Starting attempt 3 of 4
[2024-05-01T17:36:41.874+0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_debug> on 2024-05-01 12:35:18.514753+00:00
[2024-05-01T17:36:41.881+0300] {standard_task_runner.py:63} INFO - Started process 8027 to run task
[2024-05-01T17:36:41.889+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_debug', 'manual__2024-05-01T12:35:18.514753+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/bash.py', '--cfg-path', '/tmp/tmpdj48rppo']
[2024-05-01T17:36:41.894+0300] {standard_task_runner.py:91} INFO - Job 42: Subtask dbt_debug
[2024-05-01T17:36:42.487+0300] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T12:35:18.514753+00:00 [running]> on host yohanes-Satellite-Pro-C50-A363
[2024-05-01T17:36:43.790+0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T12:35:18.514753+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T12:35:18.514753+00:00'
[2024-05-01T17:36:43.791+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T17:36:44.089+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T17:36:44.090+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug']
[2024-05-01T17:36:44.107+0300] {subprocess.py:86} INFO - Output:
[2024-05-01T17:40:23.078+0300] {subprocess.py:93} INFO - [0m14:40:22  Running with dbt=1.7.13
[2024-05-01T17:40:23.373+0300] {subprocess.py:93} INFO - [0m14:40:22  dbt version: 1.7.13
[2024-05-01T17:40:23.374+0300] {subprocess.py:93} INFO - [0m14:40:22  python version: 3.8.10
[2024-05-01T17:40:23.374+0300] {subprocess.py:93} INFO - [0m14:40:22  python path: /home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/bin/python3
[2024-05-01T17:40:23.374+0300] {subprocess.py:93} INFO - [0m14:40:22  os info: Linux-5.15.0-105-generic-x86_64-with-glibc2.29
[2024-05-01T17:40:26.997+0300] {subprocess.py:93} INFO - [0m14:40:26  Using profiles dir at /home/yohanes/.dbt
[2024-05-01T17:40:27.006+0300] {subprocess.py:93} INFO - [0m14:40:27  Using profiles.yml file at /home/yohanes/.dbt/profiles.yml
[2024-05-01T17:40:27.016+0300] {subprocess.py:93} INFO - [0m14:40:27  Using dbt_project.yml file at /tmp/airflowtmp3epof3ot/dbt_project.yml
[2024-05-01T17:40:27.020+0300] {subprocess.py:93} INFO - [0m14:40:27  adapter type: postgres
[2024-05-01T17:40:27.025+0300] {subprocess.py:93} INFO - [0m14:40:27  adapter version: 1.7.13
[2024-05-01T17:40:27.029+0300] {subprocess.py:93} INFO - [0m14:40:27  Configuration:
[2024-05-01T17:40:27.031+0300] {subprocess.py:93} INFO - [0m14:40:27    profiles.yml file [[32mOK found and valid[0m]
[2024-05-01T17:40:27.033+0300] {subprocess.py:93} INFO - [0m14:40:27    dbt_project.yml file [[31mERROR not found[0m]
[2024-05-01T17:40:27.035+0300] {subprocess.py:93} INFO - [0m14:40:27  Required dependencies:
[2024-05-01T17:40:28.761+0300] {subprocess.py:93} INFO - [0m14:40:28   - git [[32mOK found[0m]
[2024-05-01T17:40:28.762+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:40:28.763+0300] {subprocess.py:93} INFO - [0m14:40:28  Connection:
[2024-05-01T17:40:28.767+0300] {subprocess.py:93} INFO - [0m14:40:28    host: localhost
[2024-05-01T17:40:28.771+0300] {subprocess.py:93} INFO - [0m14:40:28    port: 5432
[2024-05-01T17:40:28.773+0300] {subprocess.py:93} INFO - [0m14:40:28    user: postgres
[2024-05-01T17:40:28.775+0300] {subprocess.py:93} INFO - [0m14:40:28    database: traffic
[2024-05-01T17:40:28.784+0300] {subprocess.py:93} INFO - [0m14:40:28    schema: traffic_schema
[2024-05-01T17:40:28.786+0300] {subprocess.py:93} INFO - [0m14:40:28    connect_timeout: 10
[2024-05-01T17:40:28.791+0300] {subprocess.py:93} INFO - [0m14:40:28    role: None
[2024-05-01T17:40:28.796+0300] {subprocess.py:93} INFO - [0m14:40:28    search_path: None
[2024-05-01T17:40:28.804+0300] {subprocess.py:93} INFO - [0m14:40:28    keepalives_idle: 0
[2024-05-01T17:40:28.806+0300] {subprocess.py:93} INFO - [0m14:40:28    sslmode: None
[2024-05-01T17:40:28.810+0300] {subprocess.py:93} INFO - [0m14:40:28    sslcert: None
[2024-05-01T17:40:28.813+0300] {subprocess.py:93} INFO - [0m14:40:28    sslkey: None
[2024-05-01T17:40:28.815+0300] {subprocess.py:93} INFO - [0m14:40:28    sslrootcert: None
[2024-05-01T17:40:28.817+0300] {subprocess.py:93} INFO - [0m14:40:28    application_name: dbt
[2024-05-01T17:40:28.819+0300] {subprocess.py:93} INFO - [0m14:40:28    retries: 1
[2024-05-01T17:40:28.822+0300] {subprocess.py:93} INFO - [0m14:40:28  Registered adapter: postgres=1.7.13
[2024-05-01T17:40:29.111+0300] {subprocess.py:93} INFO - [0m14:40:29    Connection test: [[32mOK connection ok[0m]
[2024-05-01T17:40:29.111+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:40:29.116+0300] {subprocess.py:93} INFO - [0m14:40:29  [31m1 check failed:[0m
[2024-05-01T17:40:29.119+0300] {subprocess.py:93} INFO - [0m14:40:29  Project loading failed for the following reason:
[2024-05-01T17:40:29.120+0300] {subprocess.py:93} INFO -  project path </tmp/airflowtmp3epof3ot/dbt_project.yml> not found
[2024-05-01T17:40:29.120+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:40:34.917+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-01T17:40:35.936+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T17:40:43.431+0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-01T17:40:43.946+0300] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_debug, execution_date=20240501T123518, start_date=20240501T143633, end_date=20240501T144043
[2024-05-01T17:40:50.265+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 42 for task dbt_debug (Bash command failed. The command returned a non-zero exit code 1.; 8027)
[2024-05-01T17:40:52.343+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T17:40:56.223+0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T17:40:56.394+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
