[2024-05-01T16:04:33.835+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T16:04:34.132+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T13:04:12.949516+00:00 [queued]>
[2024-05-01T16:04:34.182+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T13:04:12.949516+00:00 [queued]>
[2024-05-01T16:04:34.182+0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2024-05-01T16:04:34.321+0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_debug> on 2024-05-01 13:04:12.949516+00:00
[2024-05-01T16:04:34.330+0300] {standard_task_runner.py:63} INFO - Started process 26409 to run task
[2024-05-01T16:04:34.342+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_debug', 'manual__2024-05-01T13:04:12.949516+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/bash.py', '--cfg-path', '/tmp/tmpjk3v15sa']
[2024-05-01T16:04:34.345+0300] {standard_task_runner.py:91} INFO - Job 12: Subtask dbt_debug
[2024-05-01T16:04:35.223+0300] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T13:04:12.949516+00:00 [running]> on host yohanes-Satellite-Pro-C50-A363
[2024-05-01T16:04:44.323+0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T13:04:12.949516+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T13:04:12.949516+00:00'
[2024-05-01T16:04:44.324+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T16:04:45.112+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T16:04:45.113+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug']
[2024-05-01T16:04:45.163+0300] {subprocess.py:86} INFO - Output:
[2024-05-01T16:06:30.842+0300] {subprocess.py:93} INFO - [0m13:06:30  Running with dbt=1.7.13
[2024-05-01T16:06:30.913+0300] {subprocess.py:93} INFO - [0m13:06:30  dbt version: 1.7.13
[2024-05-01T16:06:30.914+0300] {subprocess.py:93} INFO - [0m13:06:30  python version: 3.8.10
[2024-05-01T16:06:30.914+0300] {subprocess.py:93} INFO - [0m13:06:30  python path: /home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/bin/python3
[2024-05-01T16:06:30.914+0300] {subprocess.py:93} INFO - [0m13:06:30  os info: Linux-5.15.0-105-generic-x86_64-with-glibc2.29
[2024-05-01T16:06:34.606+0300] {subprocess.py:93} INFO - [0m13:06:34  Using profiles dir at /home/yohanes/.dbt
[2024-05-01T16:06:34.607+0300] {subprocess.py:93} INFO - [0m13:06:34  Using profiles.yml file at /home/yohanes/.dbt/profiles.yml
[2024-05-01T16:06:34.608+0300] {subprocess.py:93} INFO - [0m13:06:34  Using dbt_project.yml file at /tmp/airflowtmpx61d78wh/dbt_project.yml
[2024-05-01T16:06:34.631+0300] {subprocess.py:93} INFO - [0m13:06:34  adapter type: postgres
[2024-05-01T16:06:34.632+0300] {subprocess.py:93} INFO - [0m13:06:34  adapter version: 1.7.13
[2024-05-01T16:06:34.633+0300] {subprocess.py:93} INFO - [0m13:06:34  Configuration:
[2024-05-01T16:06:34.634+0300] {subprocess.py:93} INFO - [0m13:06:34    profiles.yml file [[32mOK found and valid[0m]
[2024-05-01T16:06:34.636+0300] {subprocess.py:93} INFO - [0m13:06:34    dbt_project.yml file [[31mERROR not found[0m]
[2024-05-01T16:06:34.637+0300] {subprocess.py:93} INFO - [0m13:06:34  Required dependencies:
[2024-05-01T16:06:35.835+0300] {subprocess.py:93} INFO - [0m13:06:35   - git [[32mOK found[0m]
[2024-05-01T16:06:35.836+0300] {subprocess.py:93} INFO - 
[2024-05-01T16:06:35.837+0300] {subprocess.py:93} INFO - [0m13:06:35  Connection:
[2024-05-01T16:06:35.839+0300] {subprocess.py:93} INFO - [0m13:06:35    host: localhost
[2024-05-01T16:06:35.840+0300] {subprocess.py:93} INFO - [0m13:06:35    port: 5432
[2024-05-01T16:06:35.842+0300] {subprocess.py:93} INFO - [0m13:06:35    user: postgres
[2024-05-01T16:06:35.844+0300] {subprocess.py:93} INFO - [0m13:06:35    database: traffic
[2024-05-01T16:06:35.845+0300] {subprocess.py:93} INFO - [0m13:06:35    schema: traffic_schema
[2024-05-01T16:06:35.847+0300] {subprocess.py:93} INFO - [0m13:06:35    connect_timeout: 10
[2024-05-01T16:06:35.850+0300] {subprocess.py:93} INFO - [0m13:06:35    role: None
[2024-05-01T16:06:35.852+0300] {subprocess.py:93} INFO - [0m13:06:35    search_path: None
[2024-05-01T16:06:35.854+0300] {subprocess.py:93} INFO - [0m13:06:35    keepalives_idle: 0
[2024-05-01T16:06:35.856+0300] {subprocess.py:93} INFO - [0m13:06:35    sslmode: None
[2024-05-01T16:06:35.857+0300] {subprocess.py:93} INFO - [0m13:06:35    sslcert: None
[2024-05-01T16:06:35.859+0300] {subprocess.py:93} INFO - [0m13:06:35    sslkey: None
[2024-05-01T16:06:35.861+0300] {subprocess.py:93} INFO - [0m13:06:35    sslrootcert: None
[2024-05-01T16:06:35.862+0300] {subprocess.py:93} INFO - [0m13:06:35    application_name: dbt
[2024-05-01T16:06:35.866+0300] {subprocess.py:93} INFO - [0m13:06:35    retries: 1
[2024-05-01T16:06:35.874+0300] {subprocess.py:93} INFO - [0m13:06:35  Registered adapter: postgres=1.7.13
[2024-05-01T16:06:35.926+0300] {subprocess.py:93} INFO - [0m13:06:35    Connection test: [[32mOK connection ok[0m]
[2024-05-01T16:06:35.926+0300] {subprocess.py:93} INFO - 
[2024-05-01T16:06:35.929+0300] {subprocess.py:93} INFO - [0m13:06:35  [31m1 check failed:[0m
[2024-05-01T16:06:35.931+0300] {subprocess.py:93} INFO - [0m13:06:35  Project loading failed for the following reason:
[2024-05-01T16:06:35.932+0300] {subprocess.py:93} INFO -  project path </tmp/airflowtmpx61d78wh/dbt_project.yml> not found
[2024-05-01T16:06:35.932+0300] {subprocess.py:93} INFO - 
[2024-05-01T16:06:44.707+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-01T16:06:44.708+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T16:06:44.733+0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-01T16:06:44.737+0300] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_debug, execution_date=20240501T130412, start_date=20240501T130434, end_date=20240501T130644
[2024-05-01T16:06:44.815+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task dbt_debug (Bash command failed. The command returned a non-zero exit code 1.; 26409)
[2024-05-01T16:06:44.864+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T16:06:49.088+0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T16:06:49.148+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
