[2024-05-01T18:06:56.253+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T18:06:56.324+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:56:27.208209+00:00 [queued]>
[2024-05-01T18:06:56.339+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:56:27.208209+00:00 [queued]>
[2024-05-01T18:06:56.339+0300] {taskinstance.py:2303} INFO - Starting attempt 3 of 4
[2024-05-01T18:06:56.554+0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_debug> on 2024-05-01 14:56:27.208209+00:00
[2024-05-01T18:06:56.558+0300] {standard_task_runner.py:63} INFO - Started process 37125 to run task
[2024-05-01T18:06:56.563+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_debug', 'manual__2024-05-01T14:56:27.208209+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/bash.py', '--cfg-path', '/tmp/tmplevl7ui4']
[2024-05-01T18:06:56.566+0300] {standard_task_runner.py:91} INFO - Job 65: Subtask dbt_debug
[2024-05-01T18:06:56.708+0300] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:56:27.208209+00:00 [running]> on host yohanes-Satellite-Pro-C50-A363
[2024-05-01T18:06:56.918+0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T14:56:27.208209+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T14:56:27.208209+00:00'
[2024-05-01T18:06:56.918+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T18:06:56.944+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T18:06:56.944+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug']
[2024-05-01T18:06:56.956+0300] {subprocess.py:86} INFO - Output:
[2024-05-01T18:07:01.229+0300] {subprocess.py:93} INFO - [0m15:07:01  Running with dbt=1.7.13
[2024-05-01T18:07:01.231+0300] {subprocess.py:93} INFO - [0m15:07:01  dbt version: 1.7.13
[2024-05-01T18:07:01.232+0300] {subprocess.py:93} INFO - [0m15:07:01  python version: 3.8.10
[2024-05-01T18:07:01.233+0300] {subprocess.py:93} INFO - [0m15:07:01  python path: /home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/bin/python3
[2024-05-01T18:07:01.234+0300] {subprocess.py:93} INFO - [0m15:07:01  os info: Linux-5.15.0-105-generic-x86_64-with-glibc2.29
[2024-05-01T18:07:01.403+0300] {subprocess.py:93} INFO - [0m15:07:01  Using profiles dir at /home/yohanes/.dbt
[2024-05-01T18:07:01.404+0300] {subprocess.py:93} INFO - [0m15:07:01  Using profiles.yml file at /home/yohanes/.dbt/profiles.yml
[2024-05-01T18:07:01.406+0300] {subprocess.py:93} INFO - [0m15:07:01  Using dbt_project.yml file at /tmp/airflowtmpe2100qa7/dbt_project.yml
[2024-05-01T18:07:01.408+0300] {subprocess.py:93} INFO - [0m15:07:01  adapter type: postgres
[2024-05-01T18:07:01.409+0300] {subprocess.py:93} INFO - [0m15:07:01  adapter version: 1.7.13
[2024-05-01T18:07:01.410+0300] {subprocess.py:93} INFO - [0m15:07:01  Configuration:
[2024-05-01T18:07:01.411+0300] {subprocess.py:93} INFO - [0m15:07:01    profiles.yml file [[32mOK found and valid[0m]
[2024-05-01T18:07:01.412+0300] {subprocess.py:93} INFO - [0m15:07:01    dbt_project.yml file [[31mERROR not found[0m]
[2024-05-01T18:07:01.414+0300] {subprocess.py:93} INFO - [0m15:07:01  Required dependencies:
[2024-05-01T18:07:01.427+0300] {subprocess.py:93} INFO - [0m15:07:01   - git [[32mOK found[0m]
[2024-05-01T18:07:01.428+0300] {subprocess.py:93} INFO - 
[2024-05-01T18:07:01.429+0300] {subprocess.py:93} INFO - [0m15:07:01  Connection:
[2024-05-01T18:07:01.430+0300] {subprocess.py:93} INFO - [0m15:07:01    host: localhost
[2024-05-01T18:07:01.431+0300] {subprocess.py:93} INFO - [0m15:07:01    port: 5432
[2024-05-01T18:07:01.433+0300] {subprocess.py:93} INFO - [0m15:07:01    user: postgres
[2024-05-01T18:07:01.434+0300] {subprocess.py:93} INFO - [0m15:07:01    database: traffic
[2024-05-01T18:07:01.435+0300] {subprocess.py:93} INFO - [0m15:07:01    schema: traffic_schema
[2024-05-01T18:07:01.437+0300] {subprocess.py:93} INFO - [0m15:07:01    connect_timeout: 10
[2024-05-01T18:07:01.438+0300] {subprocess.py:93} INFO - [0m15:07:01    role: None
[2024-05-01T18:07:01.440+0300] {subprocess.py:93} INFO - [0m15:07:01    search_path: None
[2024-05-01T18:07:01.442+0300] {subprocess.py:93} INFO - [0m15:07:01    keepalives_idle: 0
[2024-05-01T18:07:01.443+0300] {subprocess.py:93} INFO - [0m15:07:01    sslmode: None
[2024-05-01T18:07:01.444+0300] {subprocess.py:93} INFO - [0m15:07:01    sslcert: None
[2024-05-01T18:07:01.446+0300] {subprocess.py:93} INFO - [0m15:07:01    sslkey: None
[2024-05-01T18:07:01.447+0300] {subprocess.py:93} INFO - [0m15:07:01    sslrootcert: None
[2024-05-01T18:07:01.448+0300] {subprocess.py:93} INFO - [0m15:07:01    application_name: dbt
[2024-05-01T18:07:01.449+0300] {subprocess.py:93} INFO - [0m15:07:01    retries: 1
[2024-05-01T18:07:01.451+0300] {subprocess.py:93} INFO - [0m15:07:01  Registered adapter: postgres=1.7.13
[2024-05-01T18:07:01.490+0300] {subprocess.py:93} INFO - [0m15:07:01    Connection test: [[32mOK connection ok[0m]
[2024-05-01T18:07:01.490+0300] {subprocess.py:93} INFO - 
[2024-05-01T18:07:01.491+0300] {subprocess.py:93} INFO - [0m15:07:01  [31m1 check failed:[0m
[2024-05-01T18:07:01.493+0300] {subprocess.py:93} INFO - [0m15:07:01  Project loading failed for the following reason:
[2024-05-01T18:07:01.494+0300] {subprocess.py:93} INFO -  project path </tmp/airflowtmpe2100qa7/dbt_project.yml> not found
[2024-05-01T18:07:01.494+0300] {subprocess.py:93} INFO - 
[2024-05-01T18:07:05.733+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-01T18:07:05.734+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T18:07:05.767+0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-01T18:07:05.773+0300] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_debug, execution_date=20240501T145627, start_date=20240501T150656, end_date=20240501T150705
[2024-05-01T18:07:05.833+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 65 for task dbt_debug (Bash command failed. The command returned a non-zero exit code 1.; 37125)
[2024-05-01T18:07:05.868+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T18:07:05.920+0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T18:07:05.932+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
