[2024-05-01T17:56:32.672+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T17:56:32.736+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:56:27.208209+00:00 [queued]>
[2024-05-01T17:56:32.758+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:56:27.208209+00:00 [queued]>
[2024-05-01T17:56:32.758+0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2024-05-01T17:56:33.020+0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_debug> on 2024-05-01 14:56:27.208209+00:00
[2024-05-01T17:56:33.026+0300] {standard_task_runner.py:63} INFO - Started process 27552 to run task
[2024-05-01T17:56:33.033+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_debug', 'manual__2024-05-01T14:56:27.208209+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/bash.py', '--cfg-path', '/tmp/tmp6xbribgo']
[2024-05-01T17:56:33.036+0300] {standard_task_runner.py:91} INFO - Job 62: Subtask dbt_debug
[2024-05-01T17:56:33.227+0300] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:56:27.208209+00:00 [running]> on host yohanes-Satellite-Pro-C50-A363
[2024-05-01T17:56:33.513+0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T14:56:27.208209+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T14:56:27.208209+00:00'
[2024-05-01T17:56:33.514+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T17:56:33.542+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T17:56:33.542+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug']
[2024-05-01T17:56:33.555+0300] {subprocess.py:86} INFO - Output:
[2024-05-01T17:56:38.760+0300] {subprocess.py:93} INFO - [0m14:56:38  Running with dbt=1.7.13
[2024-05-01T17:56:38.764+0300] {subprocess.py:93} INFO - [0m14:56:38  dbt version: 1.7.13
[2024-05-01T17:56:38.765+0300] {subprocess.py:93} INFO - [0m14:56:38  python version: 3.8.10
[2024-05-01T17:56:38.767+0300] {subprocess.py:93} INFO - [0m14:56:38  python path: /home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/bin/python3
[2024-05-01T17:56:38.768+0300] {subprocess.py:93} INFO - [0m14:56:38  os info: Linux-5.15.0-105-generic-x86_64-with-glibc2.29
[2024-05-01T17:56:38.953+0300] {subprocess.py:93} INFO - [0m14:56:38  Using profiles dir at /home/yohanes/.dbt
[2024-05-01T17:56:38.955+0300] {subprocess.py:93} INFO - [0m14:56:38  Using profiles.yml file at /home/yohanes/.dbt/profiles.yml
[2024-05-01T17:56:38.957+0300] {subprocess.py:93} INFO - [0m14:56:38  Using dbt_project.yml file at /tmp/airflowtmpobr49h_e/dbt_project.yml
[2024-05-01T17:56:38.959+0300] {subprocess.py:93} INFO - [0m14:56:38  adapter type: postgres
[2024-05-01T17:56:38.960+0300] {subprocess.py:93} INFO - [0m14:56:38  adapter version: 1.7.13
[2024-05-01T17:56:38.961+0300] {subprocess.py:93} INFO - [0m14:56:38  Configuration:
[2024-05-01T17:56:38.962+0300] {subprocess.py:93} INFO - [0m14:56:38    profiles.yml file [[32mOK found and valid[0m]
[2024-05-01T17:56:38.963+0300] {subprocess.py:93} INFO - [0m14:56:38    dbt_project.yml file [[31mERROR not found[0m]
[2024-05-01T17:56:38.964+0300] {subprocess.py:93} INFO - [0m14:56:38  Required dependencies:
[2024-05-01T17:56:38.978+0300] {subprocess.py:93} INFO - [0m14:56:38   - git [[32mOK found[0m]
[2024-05-01T17:56:38.978+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:56:38.979+0300] {subprocess.py:93} INFO - [0m14:56:38  Connection:
[2024-05-01T17:56:38.981+0300] {subprocess.py:93} INFO - [0m14:56:38    host: localhost
[2024-05-01T17:56:38.982+0300] {subprocess.py:93} INFO - [0m14:56:38    port: 5432
[2024-05-01T17:56:38.983+0300] {subprocess.py:93} INFO - [0m14:56:38    user: postgres
[2024-05-01T17:56:38.984+0300] {subprocess.py:93} INFO - [0m14:56:38    database: traffic
[2024-05-01T17:56:38.986+0300] {subprocess.py:93} INFO - [0m14:56:38    schema: traffic_schema
[2024-05-01T17:56:38.987+0300] {subprocess.py:93} INFO - [0m14:56:38    connect_timeout: 10
[2024-05-01T17:56:38.989+0300] {subprocess.py:93} INFO - [0m14:56:38    role: None
[2024-05-01T17:56:38.992+0300] {subprocess.py:93} INFO - [0m14:56:38    search_path: None
[2024-05-01T17:56:38.992+0300] {subprocess.py:93} INFO - [0m14:56:38    keepalives_idle: 0
[2024-05-01T17:56:38.994+0300] {subprocess.py:93} INFO - [0m14:56:38    sslmode: None
[2024-05-01T17:56:38.995+0300] {subprocess.py:93} INFO - [0m14:56:38    sslcert: None
[2024-05-01T17:56:38.996+0300] {subprocess.py:93} INFO - [0m14:56:38    sslkey: None
[2024-05-01T17:56:38.997+0300] {subprocess.py:93} INFO - [0m14:56:38    sslrootcert: None
[2024-05-01T17:56:39.000+0300] {subprocess.py:93} INFO - [0m14:56:38    application_name: dbt
[2024-05-01T17:56:39.000+0300] {subprocess.py:93} INFO - [0m14:56:38    retries: 1
[2024-05-01T17:56:39.001+0300] {subprocess.py:93} INFO - [0m14:56:39  Registered adapter: postgres=1.7.13
[2024-05-01T17:56:39.045+0300] {subprocess.py:93} INFO - [0m14:56:39    Connection test: [[32mOK connection ok[0m]
[2024-05-01T17:56:39.045+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:56:39.047+0300] {subprocess.py:93} INFO - [0m14:56:39  [31m1 check failed:[0m
[2024-05-01T17:56:39.049+0300] {subprocess.py:93} INFO - [0m14:56:39  Project loading failed for the following reason:
[2024-05-01T17:56:39.049+0300] {subprocess.py:93} INFO -  project path </tmp/airflowtmpobr49h_e/dbt_project.yml> not found
[2024-05-01T17:56:39.050+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:56:40.436+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-01T17:56:40.438+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T17:56:40.465+0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-01T17:56:40.470+0300] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_debug, execution_date=20240501T145627, start_date=20240501T145632, end_date=20240501T145640
[2024-05-01T17:56:40.520+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 62 for task dbt_debug (Bash command failed. The command returned a non-zero exit code 1.; 27552)
[2024-05-01T17:56:40.561+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T17:56:40.616+0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T17:56:40.665+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
