[2024-05-01T18:01:43.468+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T18:01:43.524+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:56:27.208209+00:00 [queued]>
[2024-05-01T18:01:43.538+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:56:27.208209+00:00 [queued]>
[2024-05-01T18:01:43.539+0300] {taskinstance.py:2303} INFO - Starting attempt 2 of 4
[2024-05-01T18:01:43.751+0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_debug> on 2024-05-01 14:56:27.208209+00:00
[2024-05-01T18:01:43.758+0300] {standard_task_runner.py:63} INFO - Started process 33116 to run task
[2024-05-01T18:01:43.762+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_debug', 'manual__2024-05-01T14:56:27.208209+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/bash.py', '--cfg-path', '/tmp/tmpm29kyt67']
[2024-05-01T18:01:43.766+0300] {standard_task_runner.py:91} INFO - Job 64: Subtask dbt_debug
[2024-05-01T18:01:43.902+0300] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:56:27.208209+00:00 [running]> on host yohanes-Satellite-Pro-C50-A363
[2024-05-01T18:01:44.132+0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T14:56:27.208209+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T14:56:27.208209+00:00'
[2024-05-01T18:01:44.133+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T18:01:44.166+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T18:01:44.167+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug']
[2024-05-01T18:01:44.177+0300] {subprocess.py:86} INFO - Output:
[2024-05-01T18:01:49.018+0300] {subprocess.py:93} INFO - [0m15:01:49  Running with dbt=1.7.13
[2024-05-01T18:01:49.022+0300] {subprocess.py:93} INFO - [0m15:01:49  dbt version: 1.7.13
[2024-05-01T18:01:49.024+0300] {subprocess.py:93} INFO - [0m15:01:49  python version: 3.8.10
[2024-05-01T18:01:49.026+0300] {subprocess.py:93} INFO - [0m15:01:49  python path: /home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/bin/python3
[2024-05-01T18:01:49.027+0300] {subprocess.py:93} INFO - [0m15:01:49  os info: Linux-5.15.0-105-generic-x86_64-with-glibc2.29
[2024-05-01T18:01:49.212+0300] {subprocess.py:93} INFO - [0m15:01:49  Using profiles dir at /home/yohanes/.dbt
[2024-05-01T18:01:49.213+0300] {subprocess.py:93} INFO - [0m15:01:49  Using profiles.yml file at /home/yohanes/.dbt/profiles.yml
[2024-05-01T18:01:49.214+0300] {subprocess.py:93} INFO - [0m15:01:49  Using dbt_project.yml file at /tmp/airflowtmpuemtijzw/dbt_project.yml
[2024-05-01T18:01:49.215+0300] {subprocess.py:93} INFO - [0m15:01:49  adapter type: postgres
[2024-05-01T18:01:49.216+0300] {subprocess.py:93} INFO - [0m15:01:49  adapter version: 1.7.13
[2024-05-01T18:01:49.218+0300] {subprocess.py:93} INFO - [0m15:01:49  Configuration:
[2024-05-01T18:01:49.220+0300] {subprocess.py:93} INFO - [0m15:01:49    profiles.yml file [[32mOK found and valid[0m]
[2024-05-01T18:01:49.221+0300] {subprocess.py:93} INFO - [0m15:01:49    dbt_project.yml file [[31mERROR not found[0m]
[2024-05-01T18:01:49.222+0300] {subprocess.py:93} INFO - [0m15:01:49  Required dependencies:
[2024-05-01T18:01:49.237+0300] {subprocess.py:93} INFO - [0m15:01:49   - git [[32mOK found[0m]
[2024-05-01T18:01:49.237+0300] {subprocess.py:93} INFO - 
[2024-05-01T18:01:49.238+0300] {subprocess.py:93} INFO - [0m15:01:49  Connection:
[2024-05-01T18:01:49.239+0300] {subprocess.py:93} INFO - [0m15:01:49    host: localhost
[2024-05-01T18:01:49.240+0300] {subprocess.py:93} INFO - [0m15:01:49    port: 5432
[2024-05-01T18:01:49.242+0300] {subprocess.py:93} INFO - [0m15:01:49    user: postgres
[2024-05-01T18:01:49.243+0300] {subprocess.py:93} INFO - [0m15:01:49    database: traffic
[2024-05-01T18:01:49.244+0300] {subprocess.py:93} INFO - [0m15:01:49    schema: traffic_schema
[2024-05-01T18:01:49.245+0300] {subprocess.py:93} INFO - [0m15:01:49    connect_timeout: 10
[2024-05-01T18:01:49.246+0300] {subprocess.py:93} INFO - [0m15:01:49    role: None
[2024-05-01T18:01:49.247+0300] {subprocess.py:93} INFO - [0m15:01:49    search_path: None
[2024-05-01T18:01:49.248+0300] {subprocess.py:93} INFO - [0m15:01:49    keepalives_idle: 0
[2024-05-01T18:01:49.249+0300] {subprocess.py:93} INFO - [0m15:01:49    sslmode: None
[2024-05-01T18:01:49.250+0300] {subprocess.py:93} INFO - [0m15:01:49    sslcert: None
[2024-05-01T18:01:49.252+0300] {subprocess.py:93} INFO - [0m15:01:49    sslkey: None
[2024-05-01T18:01:49.253+0300] {subprocess.py:93} INFO - [0m15:01:49    sslrootcert: None
[2024-05-01T18:01:49.254+0300] {subprocess.py:93} INFO - [0m15:01:49    application_name: dbt
[2024-05-01T18:01:49.255+0300] {subprocess.py:93} INFO - [0m15:01:49    retries: 1
[2024-05-01T18:01:49.256+0300] {subprocess.py:93} INFO - [0m15:01:49  Registered adapter: postgres=1.7.13
[2024-05-01T18:01:49.295+0300] {subprocess.py:93} INFO - [0m15:01:49    Connection test: [[32mOK connection ok[0m]
[2024-05-01T18:01:49.296+0300] {subprocess.py:93} INFO - 
[2024-05-01T18:01:49.297+0300] {subprocess.py:93} INFO - [0m15:01:49  [31m1 check failed:[0m
[2024-05-01T18:01:49.299+0300] {subprocess.py:93} INFO - [0m15:01:49  Project loading failed for the following reason:
[2024-05-01T18:01:49.299+0300] {subprocess.py:93} INFO -  project path </tmp/airflowtmpuemtijzw/dbt_project.yml> not found
[2024-05-01T18:01:49.300+0300] {subprocess.py:93} INFO - 
[2024-05-01T18:01:51.555+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-01T18:01:51.556+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T18:01:51.590+0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-01T18:01:51.598+0300] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_debug, execution_date=20240501T145627, start_date=20240501T150143, end_date=20240501T150151
[2024-05-01T18:01:51.651+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 64 for task dbt_debug (Bash command failed. The command returned a non-zero exit code 1.; 33116)
[2024-05-01T18:01:51.687+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T18:01:51.745+0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T18:01:51.750+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
