[2024-05-01T15:57:47.084+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T15:57:47.184+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T12:34:54.560122+00:00 [queued]>
[2024-05-01T15:57:47.205+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T12:34:54.560122+00:00 [queued]>
[2024-05-01T15:57:47.206+0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2024-05-01T15:57:47.681+0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_debug> on 2024-05-01 12:34:54.560122+00:00
[2024-05-01T15:57:47.707+0300] {standard_task_runner.py:63} INFO - Started process 19408 to run task
[2024-05-01T15:57:47.755+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_debug', 'manual__2024-05-01T12:34:54.560122+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/bash.py', '--cfg-path', '/tmp/tmpyogzp_7a']
[2024-05-01T15:57:47.791+0300] {standard_task_runner.py:91} INFO - Job 11: Subtask dbt_debug
[2024-05-01T15:57:55.877+0300] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T12:34:54.560122+00:00 [running]> on host yohanes-Satellite-Pro-C50-A363
[2024-05-01T15:58:04.092+0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T12:34:54.560122+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T12:34:54.560122+00:00'
[2024-05-01T15:58:04.093+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T15:58:04.111+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T15:58:04.112+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug']
[2024-05-01T15:58:04.182+0300] {subprocess.py:86} INFO - Output:
[2024-05-01T16:01:23.201+0300] {subprocess.py:93} INFO - [0m13:01:23  Running with dbt=1.7.13
[2024-05-01T16:01:23.244+0300] {subprocess.py:93} INFO - [0m13:01:23  dbt version: 1.7.13
[2024-05-01T16:01:23.244+0300] {subprocess.py:93} INFO - [0m13:01:23  python version: 3.8.10
[2024-05-01T16:01:23.245+0300] {subprocess.py:93} INFO - [0m13:01:23  python path: /home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/bin/python3
[2024-05-01T16:01:23.245+0300] {subprocess.py:93} INFO - [0m13:01:23  os info: Linux-5.15.0-105-generic-x86_64-with-glibc2.29
[2024-05-01T16:01:32.574+0300] {subprocess.py:93} INFO - [0m13:01:32  Using profiles dir at /home/yohanes/.dbt
[2024-05-01T16:01:32.577+0300] {subprocess.py:93} INFO - [0m13:01:32  Using profiles.yml file at /home/yohanes/.dbt/profiles.yml
[2024-05-01T16:01:32.579+0300] {subprocess.py:93} INFO - [0m13:01:32  Using dbt_project.yml file at /tmp/airflowtmp3irgnn6u/dbt_project.yml
[2024-05-01T16:01:33.194+0300] {subprocess.py:93} INFO - [0m13:01:33  adapter type: postgres
[2024-05-01T16:01:33.194+0300] {subprocess.py:93} INFO - [0m13:01:33  adapter version: 1.7.13
[2024-05-01T16:01:33.195+0300] {subprocess.py:93} INFO - [0m13:01:33  Configuration:
[2024-05-01T16:01:33.197+0300] {subprocess.py:93} INFO - [0m13:01:33    profiles.yml file [[32mOK found and valid[0m]
[2024-05-01T16:01:33.200+0300] {subprocess.py:93} INFO - [0m13:01:33    dbt_project.yml file [[31mERROR not found[0m]
[2024-05-01T16:01:33.202+0300] {subprocess.py:93} INFO - [0m13:01:33  Required dependencies:
[2024-05-01T16:01:37.350+0300] {subprocess.py:93} INFO - [0m13:01:37   - git [[32mOK found[0m]
[2024-05-01T16:01:37.351+0300] {subprocess.py:93} INFO - 
[2024-05-01T16:01:37.358+0300] {subprocess.py:93} INFO - [0m13:01:37  Connection:
[2024-05-01T16:01:37.363+0300] {subprocess.py:93} INFO - [0m13:01:37    host: localhost
[2024-05-01T16:01:37.368+0300] {subprocess.py:93} INFO - [0m13:01:37    port: 5432
[2024-05-01T16:01:37.372+0300] {subprocess.py:93} INFO - [0m13:01:37    user: postgres
[2024-05-01T16:01:37.376+0300] {subprocess.py:93} INFO - [0m13:01:37    database: traffic
[2024-05-01T16:01:37.381+0300] {subprocess.py:93} INFO - [0m13:01:37    schema: traffic_schema
[2024-05-01T16:01:37.385+0300] {subprocess.py:93} INFO - [0m13:01:37    connect_timeout: 10
[2024-05-01T16:01:37.388+0300] {subprocess.py:93} INFO - [0m13:01:37    role: None
[2024-05-01T16:01:37.391+0300] {subprocess.py:93} INFO - [0m13:01:37    search_path: None
[2024-05-01T16:01:37.394+0300] {subprocess.py:93} INFO - [0m13:01:37    keepalives_idle: 0
[2024-05-01T16:01:37.398+0300] {subprocess.py:93} INFO - [0m13:01:37    sslmode: None
[2024-05-01T16:01:37.401+0300] {subprocess.py:93} INFO - [0m13:01:37    sslcert: None
[2024-05-01T16:01:37.406+0300] {subprocess.py:93} INFO - [0m13:01:37    sslkey: None
[2024-05-01T16:01:37.409+0300] {subprocess.py:93} INFO - [0m13:01:37    sslrootcert: None
[2024-05-01T16:01:37.412+0300] {subprocess.py:93} INFO - [0m13:01:37    application_name: dbt
[2024-05-01T16:01:37.419+0300] {subprocess.py:93} INFO - [0m13:01:37    retries: 1
[2024-05-01T16:01:37.423+0300] {subprocess.py:93} INFO - [0m13:01:37  Registered adapter: postgres=1.7.13
[2024-05-01T16:01:38.462+0300] {subprocess.py:93} INFO - [0m13:01:38    Connection test: [[32mOK connection ok[0m]
[2024-05-01T16:01:38.463+0300] {subprocess.py:93} INFO - 
[2024-05-01T16:01:38.467+0300] {subprocess.py:93} INFO - [0m13:01:38  [31m1 check failed:[0m
[2024-05-01T16:01:38.471+0300] {subprocess.py:93} INFO - [0m13:01:38  Project loading failed for the following reason:
[2024-05-01T16:01:38.472+0300] {subprocess.py:93} INFO -  project path </tmp/airflowtmp3irgnn6u/dbt_project.yml> not found
[2024-05-01T16:01:38.472+0300] {subprocess.py:93} INFO - 
[2024-05-01T16:01:43.792+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-01T16:01:43.867+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T16:01:43.895+0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-01T16:01:43.900+0300] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_debug, execution_date=20240501T123454, start_date=20240501T125747, end_date=20240501T130143
[2024-05-01T16:01:44.373+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task dbt_debug (Bash command failed. The command returned a non-zero exit code 1.; 19408)
[2024-05-01T16:01:44.387+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T16:01:48.286+0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T16:01:48.406+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
