[2024-05-01T17:36:33.933+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T17:36:34.134+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:15:25.962723+00:00 [queued]>
[2024-05-01T17:36:34.281+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:15:25.962723+00:00 [queued]>
[2024-05-01T17:36:34.286+0300] {taskinstance.py:2303} INFO - Starting attempt 2 of 4
[2024-05-01T17:36:37.296+0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_debug> on 2024-05-01 14:15:25.962723+00:00
[2024-05-01T17:36:37.301+0300] {standard_task_runner.py:63} INFO - Started process 7922 to run task
[2024-05-01T17:36:37.312+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_debug', 'manual__2024-05-01T14:15:25.962723+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/bash.py', '--cfg-path', '/tmp/tmp_ftwsj67']
[2024-05-01T17:36:37.316+0300] {standard_task_runner.py:91} INFO - Job 46: Subtask dbt_debug
[2024-05-01T17:36:38.129+0300] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:15:25.962723+00:00 [running]> on host yohanes-Satellite-Pro-C50-A363
[2024-05-01T17:36:41.623+0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T14:15:25.962723+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T14:15:25.962723+00:00'
[2024-05-01T17:36:41.624+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T17:36:44.090+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T17:36:44.121+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug']
[2024-05-01T17:36:44.140+0300] {subprocess.py:86} INFO - Output:
[2024-05-01T17:40:22.918+0300] {subprocess.py:93} INFO - [0m14:40:22  Running with dbt=1.7.13
[2024-05-01T17:40:23.585+0300] {subprocess.py:93} INFO - [0m14:40:22  dbt version: 1.7.13
[2024-05-01T17:40:23.586+0300] {subprocess.py:93} INFO - [0m14:40:22  python version: 3.8.10
[2024-05-01T17:40:23.586+0300] {subprocess.py:93} INFO - [0m14:40:22  python path: /home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/bin/python3
[2024-05-01T17:40:23.587+0300] {subprocess.py:93} INFO - [0m14:40:22  os info: Linux-5.15.0-105-generic-x86_64-with-glibc2.29
[2024-05-01T17:40:27.050+0300] {subprocess.py:93} INFO - [0m14:40:27  Using profiles dir at /home/yohanes/.dbt
[2024-05-01T17:40:27.052+0300] {subprocess.py:93} INFO - [0m14:40:27  Using profiles.yml file at /home/yohanes/.dbt/profiles.yml
[2024-05-01T17:40:27.055+0300] {subprocess.py:93} INFO - [0m14:40:27  Using dbt_project.yml file at /tmp/airflowtmp6yqtkf_k/dbt_project.yml
[2024-05-01T17:40:27.057+0300] {subprocess.py:93} INFO - [0m14:40:27  adapter type: postgres
[2024-05-01T17:40:27.059+0300] {subprocess.py:93} INFO - [0m14:40:27  adapter version: 1.7.13
[2024-05-01T17:40:27.062+0300] {subprocess.py:93} INFO - [0m14:40:27  Configuration:
[2024-05-01T17:40:27.063+0300] {subprocess.py:93} INFO - [0m14:40:27    profiles.yml file [[32mOK found and valid[0m]
[2024-05-01T17:40:27.065+0300] {subprocess.py:93} INFO - [0m14:40:27    dbt_project.yml file [[31mERROR not found[0m]
[2024-05-01T17:40:27.066+0300] {subprocess.py:93} INFO - [0m14:40:27  Required dependencies:
[2024-05-01T17:40:28.740+0300] {subprocess.py:93} INFO - [0m14:40:28   - git [[32mOK found[0m]
[2024-05-01T17:40:28.740+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:40:28.743+0300] {subprocess.py:93} INFO - [0m14:40:28  Connection:
[2024-05-01T17:40:28.745+0300] {subprocess.py:93} INFO - [0m14:40:28    host: localhost
[2024-05-01T17:40:28.747+0300] {subprocess.py:93} INFO - [0m14:40:28    port: 5432
[2024-05-01T17:40:28.750+0300] {subprocess.py:93} INFO - [0m14:40:28    user: postgres
[2024-05-01T17:40:28.752+0300] {subprocess.py:93} INFO - [0m14:40:28    database: traffic
[2024-05-01T17:40:28.754+0300] {subprocess.py:93} INFO - [0m14:40:28    schema: traffic_schema
[2024-05-01T17:40:28.757+0300] {subprocess.py:93} INFO - [0m14:40:28    connect_timeout: 10
[2024-05-01T17:40:28.759+0300] {subprocess.py:93} INFO - [0m14:40:28    role: None
[2024-05-01T17:40:28.765+0300] {subprocess.py:93} INFO - [0m14:40:28    search_path: None
[2024-05-01T17:40:28.769+0300] {subprocess.py:93} INFO - [0m14:40:28    keepalives_idle: 0
[2024-05-01T17:40:28.778+0300] {subprocess.py:93} INFO - [0m14:40:28    sslmode: None
[2024-05-01T17:40:28.780+0300] {subprocess.py:93} INFO - [0m14:40:28    sslcert: None
[2024-05-01T17:40:28.783+0300] {subprocess.py:93} INFO - [0m14:40:28    sslkey: None
[2024-05-01T17:40:28.789+0300] {subprocess.py:93} INFO - [0m14:40:28    sslrootcert: None
[2024-05-01T17:40:28.793+0300] {subprocess.py:93} INFO - [0m14:40:28    application_name: dbt
[2024-05-01T17:40:28.799+0300] {subprocess.py:93} INFO - [0m14:40:28    retries: 1
[2024-05-01T17:40:28.803+0300] {subprocess.py:93} INFO - [0m14:40:28  Registered adapter: postgres=1.7.13
[2024-05-01T17:40:29.098+0300] {subprocess.py:93} INFO - [0m14:40:29    Connection test: [[32mOK connection ok[0m]
[2024-05-01T17:40:29.099+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:40:29.100+0300] {subprocess.py:93} INFO - [0m14:40:29  [31m1 check failed:[0m
[2024-05-01T17:40:29.104+0300] {subprocess.py:93} INFO - [0m14:40:29  Project loading failed for the following reason:
[2024-05-01T17:40:29.105+0300] {subprocess.py:93} INFO -  project path </tmp/airflowtmp6yqtkf_k/dbt_project.yml> not found
[2024-05-01T17:40:29.105+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:40:34.905+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-01T17:40:35.177+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T17:40:37.592+0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-01T17:40:39.528+0300] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_debug, execution_date=20240501T141525, start_date=20240501T143634, end_date=20240501T144039
[2024-05-01T17:40:50.442+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 46 for task dbt_debug (Bash command failed. The command returned a non-zero exit code 1.; 7922)
[2024-05-01T17:40:52.216+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T17:40:56.493+0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T17:40:56.705+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
