[2024-05-01T17:51:24.428+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T17:51:24.494+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:15:25.962723+00:00 [queued]>
[2024-05-01T17:51:24.513+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:15:25.962723+00:00 [queued]>
[2024-05-01T17:51:24.514+0300] {taskinstance.py:2303} INFO - Starting attempt 4 of 4
[2024-05-01T17:51:24.749+0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_debug> on 2024-05-01 14:15:25.962723+00:00
[2024-05-01T17:51:24.754+0300] {standard_task_runner.py:63} INFO - Started process 22261 to run task
[2024-05-01T17:51:24.759+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_debug', 'manual__2024-05-01T14:15:25.962723+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/bash.py', '--cfg-path', '/tmp/tmp6oofogrt']
[2024-05-01T17:51:24.763+0300] {standard_task_runner.py:91} INFO - Job 60: Subtask dbt_debug
[2024-05-01T17:51:24.907+0300] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:15:25.962723+00:00 [running]> on host yohanes-Satellite-Pro-C50-A363
[2024-05-01T17:51:25.140+0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T14:15:25.962723+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T14:15:25.962723+00:00'
[2024-05-01T17:51:25.141+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T17:51:25.176+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T17:51:25.178+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug']
[2024-05-01T17:51:25.191+0300] {subprocess.py:86} INFO - Output:
[2024-05-01T17:51:30.388+0300] {subprocess.py:93} INFO - [0m14:51:30  Running with dbt=1.7.13
[2024-05-01T17:51:30.391+0300] {subprocess.py:93} INFO - [0m14:51:30  dbt version: 1.7.13
[2024-05-01T17:51:30.392+0300] {subprocess.py:93} INFO - [0m14:51:30  python version: 3.8.10
[2024-05-01T17:51:30.394+0300] {subprocess.py:93} INFO - [0m14:51:30  python path: /home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/bin/python3
[2024-05-01T17:51:30.395+0300] {subprocess.py:93} INFO - [0m14:51:30  os info: Linux-5.15.0-105-generic-x86_64-with-glibc2.29
[2024-05-01T17:51:30.574+0300] {subprocess.py:93} INFO - [0m14:51:30  Using profiles dir at /home/yohanes/.dbt
[2024-05-01T17:51:30.576+0300] {subprocess.py:93} INFO - [0m14:51:30  Using profiles.yml file at /home/yohanes/.dbt/profiles.yml
[2024-05-01T17:51:30.577+0300] {subprocess.py:93} INFO - [0m14:51:30  Using dbt_project.yml file at /tmp/airflowtmpq_iqxq7n/dbt_project.yml
[2024-05-01T17:51:30.578+0300] {subprocess.py:93} INFO - [0m14:51:30  adapter type: postgres
[2024-05-01T17:51:30.579+0300] {subprocess.py:93} INFO - [0m14:51:30  adapter version: 1.7.13
[2024-05-01T17:51:30.581+0300] {subprocess.py:93} INFO - [0m14:51:30  Configuration:
[2024-05-01T17:51:30.583+0300] {subprocess.py:93} INFO - [0m14:51:30    profiles.yml file [[32mOK found and valid[0m]
[2024-05-01T17:51:30.584+0300] {subprocess.py:93} INFO - [0m14:51:30    dbt_project.yml file [[31mERROR not found[0m]
[2024-05-01T17:51:30.586+0300] {subprocess.py:93} INFO - [0m14:51:30  Required dependencies:
[2024-05-01T17:51:30.601+0300] {subprocess.py:93} INFO - [0m14:51:30   - git [[32mOK found[0m]
[2024-05-01T17:51:30.602+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:51:30.603+0300] {subprocess.py:93} INFO - [0m14:51:30  Connection:
[2024-05-01T17:51:30.604+0300] {subprocess.py:93} INFO - [0m14:51:30    host: localhost
[2024-05-01T17:51:30.606+0300] {subprocess.py:93} INFO - [0m14:51:30    port: 5432
[2024-05-01T17:51:30.608+0300] {subprocess.py:93} INFO - [0m14:51:30    user: postgres
[2024-05-01T17:51:30.609+0300] {subprocess.py:93} INFO - [0m14:51:30    database: traffic
[2024-05-01T17:51:30.610+0300] {subprocess.py:93} INFO - [0m14:51:30    schema: traffic_schema
[2024-05-01T17:51:30.612+0300] {subprocess.py:93} INFO - [0m14:51:30    connect_timeout: 10
[2024-05-01T17:51:30.613+0300] {subprocess.py:93} INFO - [0m14:51:30    role: None
[2024-05-01T17:51:30.616+0300] {subprocess.py:93} INFO - [0m14:51:30    search_path: None
[2024-05-01T17:51:30.624+0300] {subprocess.py:93} INFO - [0m14:51:30    keepalives_idle: 0
[2024-05-01T17:51:30.625+0300] {subprocess.py:93} INFO - [0m14:51:30    sslmode: None
[2024-05-01T17:51:30.625+0300] {subprocess.py:93} INFO - [0m14:51:30    sslcert: None
[2024-05-01T17:51:30.626+0300] {subprocess.py:93} INFO - [0m14:51:30    sslkey: None
[2024-05-01T17:51:30.626+0300] {subprocess.py:93} INFO - [0m14:51:30    sslrootcert: None
[2024-05-01T17:51:30.626+0300] {subprocess.py:93} INFO - [0m14:51:30    application_name: dbt
[2024-05-01T17:51:30.627+0300] {subprocess.py:93} INFO - [0m14:51:30    retries: 1
[2024-05-01T17:51:30.628+0300] {subprocess.py:93} INFO - [0m14:51:30  Registered adapter: postgres=1.7.13
[2024-05-01T17:51:30.672+0300] {subprocess.py:93} INFO - [0m14:51:30    Connection test: [[32mOK connection ok[0m]
[2024-05-01T17:51:30.672+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:51:30.673+0300] {subprocess.py:93} INFO - [0m14:51:30  [31m1 check failed:[0m
[2024-05-01T17:51:30.675+0300] {subprocess.py:93} INFO - [0m14:51:30  Project loading failed for the following reason:
[2024-05-01T17:51:30.675+0300] {subprocess.py:93} INFO -  project path </tmp/airflowtmpq_iqxq7n/dbt_project.yml> not found
[2024-05-01T17:51:30.676+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:51:32.357+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-01T17:51:32.359+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T17:51:32.404+0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-01T17:51:32.413+0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dbt_dag, task_id=dbt_debug, execution_date=20240501T141525, start_date=20240501T145124, end_date=20240501T145132
[2024-05-01T17:51:32.461+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 60 for task dbt_debug (Bash command failed. The command returned a non-zero exit code 1.; 22261)
[2024-05-01T17:51:32.487+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T17:51:32.554+0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T17:51:32.571+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
