[2024-05-01T17:45:41.493+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T17:45:41.660+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:15:25.962723+00:00 [queued]>
[2024-05-01T17:45:41.709+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:15:25.962723+00:00 [queued]>
[2024-05-01T17:45:41.709+0300] {taskinstance.py:2303} INFO - Starting attempt 3 of 4
[2024-05-01T17:45:42.408+0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_debug> on 2024-05-01 14:15:25.962723+00:00
[2024-05-01T17:45:42.429+0300] {standard_task_runner.py:63} INFO - Started process 15031 to run task
[2024-05-01T17:45:42.448+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_debug', 'manual__2024-05-01T14:15:25.962723+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/bash.py', '--cfg-path', '/tmp/tmpja9r1xep']
[2024-05-01T17:45:42.454+0300] {standard_task_runner.py:91} INFO - Job 52: Subtask dbt_debug
[2024-05-01T17:45:42.843+0300] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:15:25.962723+00:00 [running]> on host yohanes-Satellite-Pro-C50-A363
[2024-05-01T17:45:43.346+0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T14:15:25.962723+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T14:15:25.962723+00:00'
[2024-05-01T17:45:43.349+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T17:45:43.497+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T17:45:43.499+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug']
[2024-05-01T17:45:43.532+0300] {subprocess.py:86} INFO - Output:
[2024-05-01T17:46:09.705+0300] {subprocess.py:93} INFO - [0m14:46:09  Running with dbt=1.7.13
[2024-05-01T17:46:09.717+0300] {subprocess.py:93} INFO - [0m14:46:09  dbt version: 1.7.13
[2024-05-01T17:46:09.727+0300] {subprocess.py:93} INFO - [0m14:46:09  python version: 3.8.10
[2024-05-01T17:46:09.744+0300] {subprocess.py:93} INFO - [0m14:46:09  python path: /home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/bin/python3
[2024-05-01T17:46:09.747+0300] {subprocess.py:93} INFO - [0m14:46:09  os info: Linux-5.15.0-105-generic-x86_64-with-glibc2.29
[2024-05-01T17:46:14.665+0300] {subprocess.py:93} INFO - [0m14:46:14  Using profiles dir at /home/yohanes/.dbt
[2024-05-01T17:46:14.958+0300] {subprocess.py:93} INFO - [0m14:46:14  Using profiles.yml file at /home/yohanes/.dbt/profiles.yml
[2024-05-01T17:46:14.959+0300] {subprocess.py:93} INFO - [0m14:46:14  Using dbt_project.yml file at /tmp/airflowtmp4qc8vipx/dbt_project.yml
[2024-05-01T17:46:14.959+0300] {subprocess.py:93} INFO - [0m14:46:14  adapter type: postgres
[2024-05-01T17:46:14.960+0300] {subprocess.py:93} INFO - [0m14:46:14  adapter version: 1.7.13
[2024-05-01T17:46:14.960+0300] {subprocess.py:93} INFO - [0m14:46:14  Configuration:
[2024-05-01T17:46:14.960+0300] {subprocess.py:93} INFO - [0m14:46:14    profiles.yml file [[32mOK found and valid[0m]
[2024-05-01T17:46:14.961+0300] {subprocess.py:93} INFO - [0m14:46:14    dbt_project.yml file [[31mERROR not found[0m]
[2024-05-01T17:46:14.961+0300] {subprocess.py:93} INFO - [0m14:46:14  Required dependencies:
[2024-05-01T17:46:15.502+0300] {subprocess.py:93} INFO - [0m14:46:15   - git [[32mOK found[0m]
[2024-05-01T17:46:15.503+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:46:15.508+0300] {subprocess.py:93} INFO - [0m14:46:15  Connection:
[2024-05-01T17:46:15.530+0300] {subprocess.py:93} INFO - [0m14:46:15    host: localhost
[2024-05-01T17:46:15.535+0300] {subprocess.py:93} INFO - [0m14:46:15    port: 5432
[2024-05-01T17:46:15.548+0300] {subprocess.py:93} INFO - [0m14:46:15    user: postgres
[2024-05-01T17:46:15.559+0300] {subprocess.py:93} INFO - [0m14:46:15    database: traffic
[2024-05-01T17:46:15.574+0300] {subprocess.py:93} INFO - [0m14:46:15    schema: traffic_schema
[2024-05-01T17:46:15.579+0300] {subprocess.py:93} INFO - [0m14:46:15    connect_timeout: 10
[2024-05-01T17:46:15.595+0300] {subprocess.py:93} INFO - [0m14:46:15    role: None
[2024-05-01T17:46:15.612+0300] {subprocess.py:93} INFO - [0m14:46:15    search_path: None
[2024-05-01T17:46:15.630+0300] {subprocess.py:93} INFO - [0m14:46:15    keepalives_idle: 0
[2024-05-01T17:46:15.644+0300] {subprocess.py:93} INFO - [0m14:46:15    sslmode: None
[2024-05-01T17:46:15.648+0300] {subprocess.py:93} INFO - [0m14:46:15    sslcert: None
[2024-05-01T17:46:15.663+0300] {subprocess.py:93} INFO - [0m14:46:15    sslkey: None
[2024-05-01T17:46:15.674+0300] {subprocess.py:93} INFO - [0m14:46:15    sslrootcert: None
[2024-05-01T17:46:15.679+0300] {subprocess.py:93} INFO - [0m14:46:15    application_name: dbt
[2024-05-01T17:46:15.682+0300] {subprocess.py:93} INFO - [0m14:46:15    retries: 1
[2024-05-01T17:46:15.686+0300] {subprocess.py:93} INFO - [0m14:46:15  Registered adapter: postgres=1.7.13
[2024-05-01T17:46:15.938+0300] {subprocess.py:93} INFO - [0m14:46:15    Connection test: [[32mOK connection ok[0m]
[2024-05-01T17:46:15.938+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:46:15.941+0300] {subprocess.py:93} INFO - [0m14:46:15  [31m1 check failed:[0m
[2024-05-01T17:46:15.944+0300] {subprocess.py:93} INFO - [0m14:46:15  Project loading failed for the following reason:
[2024-05-01T17:46:15.945+0300] {subprocess.py:93} INFO -  project path </tmp/airflowtmp4qc8vipx/dbt_project.yml> not found
[2024-05-01T17:46:15.945+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:46:18.960+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-01T17:46:18.962+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T17:46:19.013+0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-01T17:46:19.225+0300] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_debug, execution_date=20240501T141525, start_date=20240501T144541, end_date=20240501T144619
[2024-05-01T17:46:19.323+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 52 for task dbt_debug (Bash command failed. The command returned a non-zero exit code 1.; 15031)
[2024-05-01T17:46:19.352+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T17:46:19.667+0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T17:46:19.757+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
