[2024-05-01T17:45:46.046+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T17:45:46.241+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T12:35:11.880413+00:00 [queued]>
[2024-05-01T17:45:46.266+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T12:35:11.880413+00:00 [queued]>
[2024-05-01T17:45:46.267+0300] {taskinstance.py:2303} INFO - Starting attempt 4 of 4
[2024-05-01T17:45:46.998+0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_debug> on 2024-05-01 12:35:11.880413+00:00
[2024-05-01T17:45:47.005+0300] {standard_task_runner.py:63} INFO - Started process 15253 to run task
[2024-05-01T17:45:47.020+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_debug', 'manual__2024-05-01T12:35:11.880413+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/bash.py', '--cfg-path', '/tmp/tmp_54tuqkd']
[2024-05-01T17:45:47.023+0300] {standard_task_runner.py:91} INFO - Job 56: Subtask dbt_debug
[2024-05-01T17:45:47.528+0300] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T12:35:11.880413+00:00 [running]> on host yohanes-Satellite-Pro-C50-A363
[2024-05-01T17:45:48.568+0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T12:35:11.880413+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T12:35:11.880413+00:00'
[2024-05-01T17:45:48.571+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T17:45:48.830+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T17:45:48.843+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug']
[2024-05-01T17:45:49.021+0300] {subprocess.py:86} INFO - Output:
[2024-05-01T17:46:09.888+0300] {subprocess.py:93} INFO - [0m14:46:09  Running with dbt=1.7.13
[2024-05-01T17:46:09.892+0300] {subprocess.py:93} INFO - [0m14:46:09  dbt version: 1.7.13
[2024-05-01T17:46:09.893+0300] {subprocess.py:93} INFO - [0m14:46:09  python version: 3.8.10
[2024-05-01T17:46:09.895+0300] {subprocess.py:93} INFO - [0m14:46:09  python path: /home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/bin/python3
[2024-05-01T17:46:09.897+0300] {subprocess.py:93} INFO - [0m14:46:09  os info: Linux-5.15.0-105-generic-x86_64-with-glibc2.29
[2024-05-01T17:46:14.869+0300] {subprocess.py:93} INFO - [0m14:46:14  Using profiles dir at /home/yohanes/.dbt
[2024-05-01T17:46:14.946+0300] {subprocess.py:93} INFO - [0m14:46:14  Using profiles.yml file at /home/yohanes/.dbt/profiles.yml
[2024-05-01T17:46:14.947+0300] {subprocess.py:93} INFO - [0m14:46:14  Using dbt_project.yml file at /tmp/airflowtmp2_mkmuhy/dbt_project.yml
[2024-05-01T17:46:14.947+0300] {subprocess.py:93} INFO - [0m14:46:14  adapter type: postgres
[2024-05-01T17:46:14.948+0300] {subprocess.py:93} INFO - [0m14:46:14  adapter version: 1.7.13
[2024-05-01T17:46:14.948+0300] {subprocess.py:93} INFO - [0m14:46:14  Configuration:
[2024-05-01T17:46:14.950+0300] {subprocess.py:93} INFO - [0m14:46:14    profiles.yml file [[32mOK found and valid[0m]
[2024-05-01T17:46:14.950+0300] {subprocess.py:93} INFO - [0m14:46:14    dbt_project.yml file [[31mERROR not found[0m]
[2024-05-01T17:46:14.951+0300] {subprocess.py:93} INFO - [0m14:46:14  Required dependencies:
[2024-05-01T17:46:15.500+0300] {subprocess.py:93} INFO - [0m14:46:15   - git [[32mOK found[0m]
[2024-05-01T17:46:15.501+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:46:15.510+0300] {subprocess.py:93} INFO - [0m14:46:15  Connection:
[2024-05-01T17:46:15.521+0300] {subprocess.py:93} INFO - [0m14:46:15    host: localhost
[2024-05-01T17:46:15.526+0300] {subprocess.py:93} INFO - [0m14:46:15    port: 5432
[2024-05-01T17:46:15.538+0300] {subprocess.py:93} INFO - [0m14:46:15    user: postgres
[2024-05-01T17:46:15.551+0300] {subprocess.py:93} INFO - [0m14:46:15    database: traffic
[2024-05-01T17:46:15.565+0300] {subprocess.py:93} INFO - [0m14:46:15    schema: traffic_schema
[2024-05-01T17:46:15.581+0300] {subprocess.py:93} INFO - [0m14:46:15    connect_timeout: 10
[2024-05-01T17:46:15.597+0300] {subprocess.py:93} INFO - [0m14:46:15    role: None
[2024-05-01T17:46:15.613+0300] {subprocess.py:93} INFO - [0m14:46:15    search_path: None
[2024-05-01T17:46:15.626+0300] {subprocess.py:93} INFO - [0m14:46:15    keepalives_idle: 0
[2024-05-01T17:46:15.633+0300] {subprocess.py:93} INFO - [0m14:46:15    sslmode: None
[2024-05-01T17:46:15.650+0300] {subprocess.py:93} INFO - [0m14:46:15    sslcert: None
[2024-05-01T17:46:15.655+0300] {subprocess.py:93} INFO - [0m14:46:15    sslkey: None
[2024-05-01T17:46:15.666+0300] {subprocess.py:93} INFO - [0m14:46:15    sslrootcert: None
[2024-05-01T17:46:15.676+0300] {subprocess.py:93} INFO - [0m14:46:15    application_name: dbt
[2024-05-01T17:46:15.679+0300] {subprocess.py:93} INFO - [0m14:46:15    retries: 1
[2024-05-01T17:46:15.685+0300] {subprocess.py:93} INFO - [0m14:46:15  Registered adapter: postgres=1.7.13
[2024-05-01T17:46:15.874+0300] {subprocess.py:93} INFO - [0m14:46:15    Connection test: [[32mOK connection ok[0m]
[2024-05-01T17:46:15.875+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:46:15.878+0300] {subprocess.py:93} INFO - [0m14:46:15  [31m1 check failed:[0m
[2024-05-01T17:46:15.884+0300] {subprocess.py:93} INFO - [0m14:46:15  Project loading failed for the following reason:
[2024-05-01T17:46:15.891+0300] {subprocess.py:93} INFO -  project path </tmp/airflowtmp2_mkmuhy/dbt_project.yml> not found
[2024-05-01T17:46:15.891+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:46:20.375+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-01T17:46:20.377+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T17:46:20.503+0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-01T17:46:20.511+0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dbt_dag, task_id=dbt_debug, execution_date=20240501T123511, start_date=20240501T144546, end_date=20240501T144620
[2024-05-01T17:46:21.047+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 56 for task dbt_debug (Bash command failed. The command returned a non-zero exit code 1.; 15253)
[2024-05-01T17:46:21.089+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T17:46:21.165+0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T17:46:21.303+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
