[2024-05-01T18:22:56.611+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T18:22:56.950+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T15:22:54.243406+00:00 [queued]>
[2024-05-01T18:22:57.032+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T15:22:54.243406+00:00 [queued]>
[2024-05-01T18:22:57.037+0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-01T18:22:57.365+0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_debug> on 2024-05-01 15:22:54.243406+00:00
[2024-05-01T18:22:57.373+0300] {standard_task_runner.py:63} INFO - Started process 48087 to run task
[2024-05-01T18:22:57.401+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_debug', 'manual__2024-05-01T15:22:54.243406+00:00', '--job-id', '2', '--raw', '--subdir', '/home/yohanes/airflow/dags/bash.py', '--cfg-path', '/tmp/tmp3el_k3ht']
[2024-05-01T18:22:57.405+0300] {standard_task_runner.py:91} INFO - Job 2: Subtask dbt_debug
[2024-05-01T18:22:58.063+0300] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T15:22:54.243406+00:00 [running]> on host yohanes-Satellite-Pro-C50-A363
[2024-05-01T18:22:59.399+0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T15:22:54.243406+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T15:22:54.243406+00:00'
[2024-05-01T18:22:59.400+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T18:23:00.702+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T18:23:00.797+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug']
[2024-05-01T18:23:00.809+0300] {subprocess.py:86} INFO - Output:
[2024-05-01T18:23:29.352+0300] {subprocess.py:93} INFO - [0m15:23:29  Running with dbt=1.7.13
[2024-05-01T18:23:29.356+0300] {subprocess.py:93} INFO - [0m15:23:29  dbt version: 1.7.13
[2024-05-01T18:23:29.359+0300] {subprocess.py:93} INFO - [0m15:23:29  python version: 3.8.10
[2024-05-01T18:23:29.362+0300] {subprocess.py:93} INFO - [0m15:23:29  python path: /home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/bin/python3
[2024-05-01T18:23:29.364+0300] {subprocess.py:93} INFO - [0m15:23:29  os info: Linux-5.15.0-105-generic-x86_64-with-glibc2.29
[2024-05-01T18:23:29.929+0300] {subprocess.py:93} INFO - [0m15:23:29  Using profiles dir at /home/yohanes/.dbt
[2024-05-01T18:23:29.932+0300] {subprocess.py:93} INFO - [0m15:23:29  Using profiles.yml file at /home/yohanes/.dbt/profiles.yml
[2024-05-01T18:23:29.936+0300] {subprocess.py:93} INFO - [0m15:23:29  Using dbt_project.yml file at /tmp/airflowtmp1sum1o7r/dbt_project.yml
[2024-05-01T18:23:29.946+0300] {subprocess.py:93} INFO - [0m15:23:29  adapter type: postgres
[2024-05-01T18:23:29.950+0300] {subprocess.py:93} INFO - [0m15:23:29  adapter version: 1.7.13
[2024-05-01T18:23:29.957+0300] {subprocess.py:93} INFO - [0m15:23:29  Configuration:
[2024-05-01T18:23:29.960+0300] {subprocess.py:93} INFO - [0m15:23:29    profiles.yml file [[32mOK found and valid[0m]
[2024-05-01T18:23:29.963+0300] {subprocess.py:93} INFO - [0m15:23:29    dbt_project.yml file [[31mERROR not found[0m]
[2024-05-01T18:23:29.977+0300] {subprocess.py:93} INFO - [0m15:23:29  Required dependencies:
[2024-05-01T18:23:30.301+0300] {subprocess.py:93} INFO - [0m15:23:30   - git [[32mOK found[0m]
[2024-05-01T18:23:30.302+0300] {subprocess.py:93} INFO - 
[2024-05-01T18:23:30.302+0300] {subprocess.py:93} INFO - [0m15:23:30  Connection:
[2024-05-01T18:23:30.304+0300] {subprocess.py:93} INFO - [0m15:23:30    host: localhost
[2024-05-01T18:23:30.305+0300] {subprocess.py:93} INFO - [0m15:23:30    port: 5432
[2024-05-01T18:23:30.306+0300] {subprocess.py:93} INFO - [0m15:23:30    user: postgres
[2024-05-01T18:23:30.307+0300] {subprocess.py:93} INFO - [0m15:23:30    database: traffic
[2024-05-01T18:23:30.307+0300] {subprocess.py:93} INFO - [0m15:23:30    schema: traffic_schema
[2024-05-01T18:23:30.308+0300] {subprocess.py:93} INFO - [0m15:23:30    connect_timeout: 10
[2024-05-01T18:23:30.309+0300] {subprocess.py:93} INFO - [0m15:23:30    role: None
[2024-05-01T18:23:30.311+0300] {subprocess.py:93} INFO - [0m15:23:30    search_path: None
[2024-05-01T18:23:30.315+0300] {subprocess.py:93} INFO - [0m15:23:30    keepalives_idle: 0
[2024-05-01T18:23:30.316+0300] {subprocess.py:93} INFO - [0m15:23:30    sslmode: None
[2024-05-01T18:23:30.317+0300] {subprocess.py:93} INFO - [0m15:23:30    sslcert: None
[2024-05-01T18:23:30.318+0300] {subprocess.py:93} INFO - [0m15:23:30    sslkey: None
[2024-05-01T18:23:30.320+0300] {subprocess.py:93} INFO - [0m15:23:30    sslrootcert: None
[2024-05-01T18:23:30.321+0300] {subprocess.py:93} INFO - [0m15:23:30    application_name: dbt
[2024-05-01T18:23:30.322+0300] {subprocess.py:93} INFO - [0m15:23:30    retries: 1
[2024-05-01T18:23:30.324+0300] {subprocess.py:93} INFO - [0m15:23:30  Registered adapter: postgres=1.7.13
[2024-05-01T18:23:30.392+0300] {subprocess.py:93} INFO - [0m15:23:30    Connection test: [[32mOK connection ok[0m]
[2024-05-01T18:23:30.393+0300] {subprocess.py:93} INFO - 
[2024-05-01T18:23:30.394+0300] {subprocess.py:93} INFO - [0m15:23:30  [31m1 check failed:[0m
[2024-05-01T18:23:30.397+0300] {subprocess.py:93} INFO - [0m15:23:30  Project loading failed for the following reason:
[2024-05-01T18:23:30.398+0300] {subprocess.py:93} INFO -  project path </tmp/airflowtmp1sum1o7r/dbt_project.yml> not found
[2024-05-01T18:23:30.398+0300] {subprocess.py:93} INFO - 
[2024-05-01T18:23:34.929+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-01T18:23:34.930+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T18:23:34.967+0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-01T18:23:34.996+0300] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_debug, execution_date=20240501T152254, start_date=20240501T152256, end_date=20240501T152334
[2024-05-01T18:23:35.069+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task dbt_debug (Bash command failed. The command returned a non-zero exit code 1.; 48087)
[2024-05-01T18:23:35.110+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T18:23:35.165+0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T18:23:35.202+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
