[2024-05-01T18:28:46.987+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T18:28:47.147+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T15:22:54.243406+00:00 [queued]>
[2024-05-01T18:28:47.201+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T15:22:54.243406+00:00 [queued]>
[2024-05-01T18:28:47.202+0300] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-01T18:28:47.694+0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_debug> on 2024-05-01 15:22:54.243406+00:00
[2024-05-01T18:28:47.698+0300] {standard_task_runner.py:63} INFO - Started process 53915 to run task
[2024-05-01T18:28:47.704+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_debug', 'manual__2024-05-01T15:22:54.243406+00:00', '--job-id', '3', '--raw', '--subdir', '/home/yohanes/airflow/dags/bash.py', '--cfg-path', '/tmp/tmpdn55b0r9']
[2024-05-01T18:28:47.707+0300] {standard_task_runner.py:91} INFO - Job 3: Subtask dbt_debug
[2024-05-01T18:28:47.851+0300] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T15:22:54.243406+00:00 [running]> on host yohanes-Satellite-Pro-C50-A363
[2024-05-01T18:28:48.083+0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T15:22:54.243406+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T15:22:54.243406+00:00'
[2024-05-01T18:28:48.084+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T18:28:48.115+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T18:28:48.116+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug']
[2024-05-01T18:28:48.126+0300] {subprocess.py:86} INFO - Output:
[2024-05-01T18:28:53.253+0300] {subprocess.py:93} INFO - [0m15:28:53  Running with dbt=1.7.13
[2024-05-01T18:28:53.258+0300] {subprocess.py:93} INFO - [0m15:28:53  dbt version: 1.7.13
[2024-05-01T18:28:53.260+0300] {subprocess.py:93} INFO - [0m15:28:53  python version: 3.8.10
[2024-05-01T18:28:53.262+0300] {subprocess.py:93} INFO - [0m15:28:53  python path: /home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/bin/python3
[2024-05-01T18:28:53.264+0300] {subprocess.py:93} INFO - [0m15:28:53  os info: Linux-5.15.0-105-generic-x86_64-with-glibc2.29
[2024-05-01T18:28:53.462+0300] {subprocess.py:93} INFO - [0m15:28:53  Using profiles dir at /home/yohanes/.dbt
[2024-05-01T18:28:53.463+0300] {subprocess.py:93} INFO - [0m15:28:53  Using profiles.yml file at /home/yohanes/.dbt/profiles.yml
[2024-05-01T18:28:53.464+0300] {subprocess.py:93} INFO - [0m15:28:53  Using dbt_project.yml file at /tmp/airflowtmpk1pnxkou/dbt_project.yml
[2024-05-01T18:28:53.466+0300] {subprocess.py:93} INFO - [0m15:28:53  adapter type: postgres
[2024-05-01T18:28:53.466+0300] {subprocess.py:93} INFO - [0m15:28:53  adapter version: 1.7.13
[2024-05-01T18:28:53.467+0300] {subprocess.py:93} INFO - [0m15:28:53  Configuration:
[2024-05-01T18:28:53.468+0300] {subprocess.py:93} INFO - [0m15:28:53    profiles.yml file [[32mOK found and valid[0m]
[2024-05-01T18:28:53.469+0300] {subprocess.py:93} INFO - [0m15:28:53    dbt_project.yml file [[31mERROR not found[0m]
[2024-05-01T18:28:53.470+0300] {subprocess.py:93} INFO - [0m15:28:53  Required dependencies:
[2024-05-01T18:28:53.486+0300] {subprocess.py:93} INFO - [0m15:28:53   - git [[32mOK found[0m]
[2024-05-01T18:28:53.486+0300] {subprocess.py:93} INFO - 
[2024-05-01T18:28:53.487+0300] {subprocess.py:93} INFO - [0m15:28:53  Connection:
[2024-05-01T18:28:53.488+0300] {subprocess.py:93} INFO - [0m15:28:53    host: localhost
[2024-05-01T18:28:53.491+0300] {subprocess.py:93} INFO - [0m15:28:53    port: 5432
[2024-05-01T18:28:53.494+0300] {subprocess.py:93} INFO - [0m15:28:53    user: postgres
[2024-05-01T18:28:53.496+0300] {subprocess.py:93} INFO - [0m15:28:53    database: traffic
[2024-05-01T18:28:53.497+0300] {subprocess.py:93} INFO - [0m15:28:53    schema: traffic_schema
[2024-05-01T18:28:53.499+0300] {subprocess.py:93} INFO - [0m15:28:53    connect_timeout: 10
[2024-05-01T18:28:53.500+0300] {subprocess.py:93} INFO - [0m15:28:53    role: None
[2024-05-01T18:28:53.502+0300] {subprocess.py:93} INFO - [0m15:28:53    search_path: None
[2024-05-01T18:28:53.503+0300] {subprocess.py:93} INFO - [0m15:28:53    keepalives_idle: 0
[2024-05-01T18:28:53.505+0300] {subprocess.py:93} INFO - [0m15:28:53    sslmode: None
[2024-05-01T18:28:53.507+0300] {subprocess.py:93} INFO - [0m15:28:53    sslcert: None
[2024-05-01T18:28:53.510+0300] {subprocess.py:93} INFO - [0m15:28:53    sslkey: None
[2024-05-01T18:28:53.514+0300] {subprocess.py:93} INFO - [0m15:28:53    sslrootcert: None
[2024-05-01T18:28:53.515+0300] {subprocess.py:93} INFO - [0m15:28:53    application_name: dbt
[2024-05-01T18:28:53.516+0300] {subprocess.py:93} INFO - [0m15:28:53    retries: 1
[2024-05-01T18:28:53.518+0300] {subprocess.py:93} INFO - [0m15:28:53  Registered adapter: postgres=1.7.13
[2024-05-01T18:28:53.562+0300] {subprocess.py:93} INFO - [0m15:28:53    Connection test: [[32mOK connection ok[0m]
[2024-05-01T18:28:53.563+0300] {subprocess.py:93} INFO - 
[2024-05-01T18:28:53.563+0300] {subprocess.py:93} INFO - [0m15:28:53  [31m1 check failed:[0m
[2024-05-01T18:28:53.565+0300] {subprocess.py:93} INFO - [0m15:28:53  Project loading failed for the following reason:
[2024-05-01T18:28:53.566+0300] {subprocess.py:93} INFO -  project path </tmp/airflowtmpk1pnxkou/dbt_project.yml> not found
[2024-05-01T18:28:53.566+0300] {subprocess.py:93} INFO - 
[2024-05-01T18:28:55.275+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-01T18:28:55.277+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T18:28:55.349+0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-01T18:28:55.357+0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dbt_dag, task_id=dbt_debug, execution_date=20240501T152254, start_date=20240501T152847, end_date=20240501T152855
[2024-05-01T18:28:55.394+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task dbt_debug (Bash command failed. The command returned a non-zero exit code 1.; 53915)
[2024-05-01T18:28:55.425+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T18:28:55.484+0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T18:28:55.494+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
