[2024-05-01T16:06:23.862+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T16:06:26.634+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T13:04:39.799822+00:00 [queued]>
[2024-05-01T16:06:27.463+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T13:04:39.799822+00:00 [queued]>
[2024-05-01T16:06:27.465+0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2024-05-01T16:06:28.114+0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_debug> on 2024-05-01 13:04:39.799822+00:00
[2024-05-01T16:06:28.120+0300] {standard_task_runner.py:63} INFO - Started process 30536 to run task
[2024-05-01T16:06:28.163+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_debug', 'manual__2024-05-01T13:04:39.799822+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/bash.py', '--cfg-path', '/tmp/tmptg82ccvs']
[2024-05-01T16:06:28.240+0300] {standard_task_runner.py:91} INFO - Job 21: Subtask dbt_debug
[2024-05-01T16:06:29.238+0300] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T13:04:39.799822+00:00 [running]> on host yohanes-Satellite-Pro-C50-A363
[2024-05-01T16:06:48.425+0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T13:04:39.799822+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T13:04:39.799822+00:00'
[2024-05-01T16:06:48.426+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T16:06:49.463+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T16:06:49.464+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug']
[2024-05-01T16:06:49.493+0300] {subprocess.py:86} INFO - Output:
[2024-05-01T16:07:04.721+0300] {subprocess.py:93} INFO - [0m13:07:04  Running with dbt=1.7.13
[2024-05-01T16:07:04.852+0300] {subprocess.py:93} INFO - [0m13:07:04  dbt version: 1.7.13
[2024-05-01T16:07:04.853+0300] {subprocess.py:93} INFO - [0m13:07:04  python version: 3.8.10
[2024-05-01T16:07:04.853+0300] {subprocess.py:93} INFO - [0m13:07:04  python path: /home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/bin/python3
[2024-05-01T16:07:04.853+0300] {subprocess.py:93} INFO - [0m13:07:04  os info: Linux-5.15.0-105-generic-x86_64-with-glibc2.29
[2024-05-01T16:07:05.187+0300] {subprocess.py:93} INFO - [0m13:07:05  Using profiles dir at /home/yohanes/.dbt
[2024-05-01T16:07:05.194+0300] {subprocess.py:93} INFO - [0m13:07:05  Using profiles.yml file at /home/yohanes/.dbt/profiles.yml
[2024-05-01T16:07:05.196+0300] {subprocess.py:93} INFO - [0m13:07:05  Using dbt_project.yml file at /tmp/airflowtmpf0ag3lw2/dbt_project.yml
[2024-05-01T16:07:05.199+0300] {subprocess.py:93} INFO - [0m13:07:05  adapter type: postgres
[2024-05-01T16:07:05.201+0300] {subprocess.py:93} INFO - [0m13:07:05  adapter version: 1.7.13
[2024-05-01T16:07:05.204+0300] {subprocess.py:93} INFO - [0m13:07:05  Configuration:
[2024-05-01T16:07:05.206+0300] {subprocess.py:93} INFO - [0m13:07:05    profiles.yml file [[32mOK found and valid[0m]
[2024-05-01T16:07:05.208+0300] {subprocess.py:93} INFO - [0m13:07:05    dbt_project.yml file [[31mERROR not found[0m]
[2024-05-01T16:07:05.211+0300] {subprocess.py:93} INFO - [0m13:07:05  Required dependencies:
[2024-05-01T16:07:05.266+0300] {subprocess.py:93} INFO - [0m13:07:05   - git [[32mOK found[0m]
[2024-05-01T16:07:05.267+0300] {subprocess.py:93} INFO - 
[2024-05-01T16:07:05.272+0300] {subprocess.py:93} INFO - [0m13:07:05  Connection:
[2024-05-01T16:07:05.290+0300] {subprocess.py:93} INFO - [0m13:07:05    host: localhost
[2024-05-01T16:07:05.292+0300] {subprocess.py:93} INFO - [0m13:07:05    port: 5432
[2024-05-01T16:07:05.294+0300] {subprocess.py:93} INFO - [0m13:07:05    user: postgres
[2024-05-01T16:07:05.296+0300] {subprocess.py:93} INFO - [0m13:07:05    database: traffic
[2024-05-01T16:07:05.307+0300] {subprocess.py:93} INFO - [0m13:07:05    schema: traffic_schema
[2024-05-01T16:07:05.308+0300] {subprocess.py:93} INFO - [0m13:07:05    connect_timeout: 10
[2024-05-01T16:07:05.312+0300] {subprocess.py:93} INFO - [0m13:07:05    role: None
[2024-05-01T16:07:05.327+0300] {subprocess.py:93} INFO - [0m13:07:05    search_path: None
[2024-05-01T16:07:05.332+0300] {subprocess.py:93} INFO - [0m13:07:05    keepalives_idle: 0
[2024-05-01T16:07:05.337+0300] {subprocess.py:93} INFO - [0m13:07:05    sslmode: None
[2024-05-01T16:07:05.343+0300] {subprocess.py:93} INFO - [0m13:07:05    sslcert: None
[2024-05-01T16:07:05.345+0300] {subprocess.py:93} INFO - [0m13:07:05    sslkey: None
[2024-05-01T16:07:05.348+0300] {subprocess.py:93} INFO - [0m13:07:05    sslrootcert: None
[2024-05-01T16:07:05.350+0300] {subprocess.py:93} INFO - [0m13:07:05    application_name: dbt
[2024-05-01T16:07:05.357+0300] {subprocess.py:93} INFO - [0m13:07:05    retries: 1
[2024-05-01T16:07:05.358+0300] {subprocess.py:93} INFO - [0m13:07:05  Registered adapter: postgres=1.7.13
[2024-05-01T16:07:05.404+0300] {subprocess.py:93} INFO - [0m13:07:05    Connection test: [[32mOK connection ok[0m]
[2024-05-01T16:07:05.405+0300] {subprocess.py:93} INFO - 
[2024-05-01T16:07:05.406+0300] {subprocess.py:93} INFO - [0m13:07:05  [31m1 check failed:[0m
[2024-05-01T16:07:05.408+0300] {subprocess.py:93} INFO - [0m13:07:05  Project loading failed for the following reason:
[2024-05-01T16:07:05.409+0300] {subprocess.py:93} INFO -  project path </tmp/airflowtmpf0ag3lw2/dbt_project.yml> not found
[2024-05-01T16:07:05.409+0300] {subprocess.py:93} INFO - 
[2024-05-01T16:07:07.162+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-01T16:07:07.163+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T16:07:07.205+0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-01T16:07:07.216+0300] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_debug, execution_date=20240501T130439, start_date=20240501T130626, end_date=20240501T130707
[2024-05-01T16:07:07.286+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task dbt_debug (Bash command failed. The command returned a non-zero exit code 1.; 30536)
[2024-05-01T16:07:07.329+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T16:07:07.525+0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T16:07:07.538+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
