[0m16:36:20.311934 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd5aa8b1fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd5a8df0bb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd5a8df0b20>]}


============================== 16:36:20.316800 | 964a3dec-dccf-44b2-a89b-b5700d46eb3b ==============================
[0m16:36:20.316800 [info ] [MainThread]: Running with dbt=1.7.13
[0m16:36:20.318128 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/home/yohanes/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --models merged_id.sql', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:36:20.319296 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/yohanes/airflow/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:36:20.321025 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.11318598, "process_user_time": 4.132886, "process_kernel_time": 0.151885, "process_mem_max_rss": "87732", "process_out_blocks": "8", "command_success": false, "process_in_blocks": "0"}
[0m16:36:20.322500 [debug] [MainThread]: Command `dbt run` failed at 16:36:20.322092 after 0.11 seconds
[0m16:36:20.323833 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd5aa8b1fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd5a8df0bb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd5a8df0b20>]}
[0m16:36:20.325893 [debug] [MainThread]: Flushing usage events
[0m16:37:14.275655 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f007dff8fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f007c539be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f007c539e50>]}


============================== 16:37:14.281445 | b356b950-fe27-45ec-a677-0d38c90634b4 ==============================
[0m16:37:14.281445 [info ] [MainThread]: Running with dbt=1.7.13
[0m16:37:14.282791 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/yohanes/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run --models merged_id.sql', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:37:14.284031 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/yohanes/airflow/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:37:14.285738 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.108463414, "process_user_time": 4.095213, "process_kernel_time": 0.151822, "process_mem_max_rss": "87892", "process_out_blocks": "8", "command_success": false, "process_in_blocks": "0"}
[0m16:37:14.287400 [debug] [MainThread]: Command `dbt run` failed at 16:37:14.286989 after 0.11 seconds
[0m16:37:14.288972 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f007dff8fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f007c539be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f007c539e50>]}
[0m16:37:14.290937 [debug] [MainThread]: Flushing usage events
[0m16:37:31.007676 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2c8421dfa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2c8275ebb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2c8275eb20>]}


============================== 16:37:31.013033 | 8fef070b-96bc-47e8-b066-1b7ad9018256 ==============================
[0m16:37:31.013033 [info ] [MainThread]: Running with dbt=1.7.13
[0m16:37:31.015343 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/yohanes/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --models merged_id.sql', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:37:31.017448 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/yohanes/airflow/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:37:31.020394 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.14626436, "process_user_time": 4.172184, "process_kernel_time": 0.155708, "process_mem_max_rss": "87676", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m16:37:31.022353 [debug] [MainThread]: Command `dbt run` failed at 16:37:31.021721 after 0.15 seconds
[0m16:37:31.024246 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2c8421dfa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2c8275ebb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2c8275eb20>]}
[0m16:37:31.026694 [debug] [MainThread]: Flushing usage events
