[2024-05-01T17:45:10.358+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T17:45:10.638+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:44:52.332667+00:00 [queued]>
[2024-05-01T17:45:10.679+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:44:52.332667+00:00 [queued]>
[2024-05-01T17:45:10.680+0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2024-05-01T17:45:11.263+0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_debug> on 2024-05-01 14:44:52.332667+00:00
[2024-05-01T17:45:11.269+0300] {standard_task_runner.py:63} INFO - Started process 14074 to run task
[2024-05-01T17:45:11.274+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_debug', 'manual__2024-05-01T14:44:52.332667+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/bash.py', '--cfg-path', '/tmp/tmpq2d2too0']
[2024-05-01T17:45:11.278+0300] {standard_task_runner.py:91} INFO - Job 48: Subtask dbt_debug
[2024-05-01T17:45:11.419+0300] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T14:44:52.332667+00:00 [running]> on host yohanes-Satellite-Pro-C50-A363
[2024-05-01T17:45:11.656+0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T14:44:52.332667+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T14:44:52.332667+00:00'
[2024-05-01T17:45:11.657+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T17:45:11.753+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T17:45:11.754+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug']
[2024-05-01T17:45:11.768+0300] {subprocess.py:86} INFO - Output:
[2024-05-01T17:45:22.435+0300] {subprocess.py:93} INFO - [0m14:45:22  Running with dbt=1.7.13
[2024-05-01T17:45:22.441+0300] {subprocess.py:93} INFO - [0m14:45:22  dbt version: 1.7.13
[2024-05-01T17:45:22.444+0300] {subprocess.py:93} INFO - [0m14:45:22  python version: 3.8.10
[2024-05-01T17:45:22.452+0300] {subprocess.py:93} INFO - [0m14:45:22  python path: /home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/bin/python3
[2024-05-01T17:45:22.457+0300] {subprocess.py:93} INFO - [0m14:45:22  os info: Linux-5.15.0-105-generic-x86_64-with-glibc2.29
[2024-05-01T17:45:22.775+0300] {subprocess.py:93} INFO - [0m14:45:22  Using profiles dir at /home/yohanes/.dbt
[2024-05-01T17:45:22.777+0300] {subprocess.py:93} INFO - [0m14:45:22  Using profiles.yml file at /home/yohanes/.dbt/profiles.yml
[2024-05-01T17:45:22.778+0300] {subprocess.py:93} INFO - [0m14:45:22  Using dbt_project.yml file at /tmp/airflowtmpw4s8xqjj/dbt_project.yml
[2024-05-01T17:45:22.779+0300] {subprocess.py:93} INFO - [0m14:45:22  adapter type: postgres
[2024-05-01T17:45:22.780+0300] {subprocess.py:93} INFO - [0m14:45:22  adapter version: 1.7.13
[2024-05-01T17:45:22.781+0300] {subprocess.py:93} INFO - [0m14:45:22  Configuration:
[2024-05-01T17:45:22.782+0300] {subprocess.py:93} INFO - [0m14:45:22    profiles.yml file [[32mOK found and valid[0m]
[2024-05-01T17:45:22.783+0300] {subprocess.py:93} INFO - [0m14:45:22    dbt_project.yml file [[31mERROR not found[0m]
[2024-05-01T17:45:22.783+0300] {subprocess.py:93} INFO - [0m14:45:22  Required dependencies:
[2024-05-01T17:45:22.800+0300] {subprocess.py:93} INFO - [0m14:45:22   - git [[32mOK found[0m]
[2024-05-01T17:45:22.800+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:45:22.801+0300] {subprocess.py:93} INFO - [0m14:45:22  Connection:
[2024-05-01T17:45:22.803+0300] {subprocess.py:93} INFO - [0m14:45:22    host: localhost
[2024-05-01T17:45:22.805+0300] {subprocess.py:93} INFO - [0m14:45:22    port: 5432
[2024-05-01T17:45:22.807+0300] {subprocess.py:93} INFO - [0m14:45:22    user: postgres
[2024-05-01T17:45:22.810+0300] {subprocess.py:93} INFO - [0m14:45:22    database: traffic
[2024-05-01T17:45:22.811+0300] {subprocess.py:93} INFO - [0m14:45:22    schema: traffic_schema
[2024-05-01T17:45:22.812+0300] {subprocess.py:93} INFO - [0m14:45:22    connect_timeout: 10
[2024-05-01T17:45:22.813+0300] {subprocess.py:93} INFO - [0m14:45:22    role: None
[2024-05-01T17:45:22.814+0300] {subprocess.py:93} INFO - [0m14:45:22    search_path: None
[2024-05-01T17:45:22.815+0300] {subprocess.py:93} INFO - [0m14:45:22    keepalives_idle: 0
[2024-05-01T17:45:22.816+0300] {subprocess.py:93} INFO - [0m14:45:22    sslmode: None
[2024-05-01T17:45:22.817+0300] {subprocess.py:93} INFO - [0m14:45:22    sslcert: None
[2024-05-01T17:45:22.818+0300] {subprocess.py:93} INFO - [0m14:45:22    sslkey: None
[2024-05-01T17:45:22.819+0300] {subprocess.py:93} INFO - [0m14:45:22    sslrootcert: None
[2024-05-01T17:45:22.820+0300] {subprocess.py:93} INFO - [0m14:45:22    application_name: dbt
[2024-05-01T17:45:22.822+0300] {subprocess.py:93} INFO - [0m14:45:22    retries: 1
[2024-05-01T17:45:22.824+0300] {subprocess.py:93} INFO - [0m14:45:22  Registered adapter: postgres=1.7.13
[2024-05-01T17:45:22.865+0300] {subprocess.py:93} INFO - [0m14:45:22    Connection test: [[32mOK connection ok[0m]
[2024-05-01T17:45:22.866+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:45:22.867+0300] {subprocess.py:93} INFO - [0m14:45:22  [31m1 check failed:[0m
[2024-05-01T17:45:22.868+0300] {subprocess.py:93} INFO - [0m14:45:22  Project loading failed for the following reason:
[2024-05-01T17:45:22.868+0300] {subprocess.py:93} INFO -  project path </tmp/airflowtmpw4s8xqjj/dbt_project.yml> not found
[2024-05-01T17:45:22.869+0300] {subprocess.py:93} INFO - 
[2024-05-01T17:45:24.435+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-01T17:45:24.436+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T17:45:24.472+0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-01T17:45:24.479+0300] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_debug, execution_date=20240501T144452, start_date=20240501T144510, end_date=20240501T144524
[2024-05-01T17:45:24.522+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 48 for task dbt_debug (Bash command failed. The command returned a non-zero exit code 1.; 14074)
[2024-05-01T17:45:24.554+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T17:45:24.616+0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T17:45:24.622+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
