[2024-05-01T15:57:46.784+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T15:57:46.979+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T12:36:08.915835+00:00 [queued]>
[2024-05-01T15:57:47.098+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T12:36:08.915835+00:00 [queued]>
[2024-05-01T15:57:47.099+0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2024-05-01T15:57:47.620+0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_debug> on 2024-05-01 12:36:08.915835+00:00
[2024-05-01T15:57:47.634+0300] {standard_task_runner.py:63} INFO - Started process 19399 to run task
[2024-05-01T15:57:47.648+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_debug', 'manual__2024-05-01T12:36:08.915835+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/bash.py', '--cfg-path', '/tmp/tmpsrh_bqdb']
[2024-05-01T15:57:47.651+0300] {standard_task_runner.py:91} INFO - Job 4: Subtask dbt_debug
[2024-05-01T15:57:47.969+0300] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_debug manual__2024-05-01T12:36:08.915835+00:00 [running]> on host yohanes-Satellite-Pro-C50-A363
[2024-05-01T15:57:55.877+0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T12:36:08.915835+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T12:36:08.915835+00:00'
[2024-05-01T15:57:56.087+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T15:58:03.549+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T15:58:03.818+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug']
[2024-05-01T15:58:04.181+0300] {subprocess.py:86} INFO - Output:
[2024-05-01T16:01:23.201+0300] {subprocess.py:93} INFO - [0m13:01:23  Running with dbt=1.7.13
[2024-05-01T16:01:23.243+0300] {subprocess.py:93} INFO - [0m13:01:23  dbt version: 1.7.13
[2024-05-01T16:01:23.244+0300] {subprocess.py:93} INFO - [0m13:01:23  python version: 3.8.10
[2024-05-01T16:01:23.244+0300] {subprocess.py:93} INFO - [0m13:01:23  python path: /home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/bin/python3
[2024-05-01T16:01:23.245+0300] {subprocess.py:93} INFO - [0m13:01:23  os info: Linux-5.15.0-105-generic-x86_64-with-glibc2.29
[2024-05-01T16:01:32.575+0300] {subprocess.py:93} INFO - [0m13:01:32  Using profiles dir at /home/yohanes/.dbt
[2024-05-01T16:01:32.578+0300] {subprocess.py:93} INFO - [0m13:01:32  Using profiles.yml file at /home/yohanes/.dbt/profiles.yml
[2024-05-01T16:01:32.582+0300] {subprocess.py:93} INFO - [0m13:01:32  Using dbt_project.yml file at /tmp/airflowtmp9x7azwoz/dbt_project.yml
[2024-05-01T16:01:33.190+0300] {subprocess.py:93} INFO - [0m13:01:33  adapter type: postgres
[2024-05-01T16:01:33.193+0300] {subprocess.py:93} INFO - [0m13:01:33  adapter version: 1.7.13
[2024-05-01T16:01:33.195+0300] {subprocess.py:93} INFO - [0m13:01:33  Configuration:
[2024-05-01T16:01:33.198+0300] {subprocess.py:93} INFO - [0m13:01:33    profiles.yml file [[32mOK found and valid[0m]
[2024-05-01T16:01:33.200+0300] {subprocess.py:93} INFO - [0m13:01:33    dbt_project.yml file [[31mERROR not found[0m]
[2024-05-01T16:01:33.202+0300] {subprocess.py:93} INFO - [0m13:01:33  Required dependencies:
[2024-05-01T16:01:37.350+0300] {subprocess.py:93} INFO - [0m13:01:37   - git [[32mOK found[0m]
[2024-05-01T16:01:37.351+0300] {subprocess.py:93} INFO - 
[2024-05-01T16:01:37.353+0300] {subprocess.py:93} INFO - [0m13:01:37  Connection:
[2024-05-01T16:01:37.356+0300] {subprocess.py:93} INFO - [0m13:01:37    host: localhost
[2024-05-01T16:01:37.358+0300] {subprocess.py:93} INFO - [0m13:01:37    port: 5432
[2024-05-01T16:01:37.361+0300] {subprocess.py:93} INFO - [0m13:01:37    user: postgres
[2024-05-01T16:01:37.363+0300] {subprocess.py:93} INFO - [0m13:01:37    database: traffic
[2024-05-01T16:01:37.366+0300] {subprocess.py:93} INFO - [0m13:01:37    schema: traffic_schema
[2024-05-01T16:01:37.369+0300] {subprocess.py:93} INFO - [0m13:01:37    connect_timeout: 10
[2024-05-01T16:01:37.371+0300] {subprocess.py:93} INFO - [0m13:01:37    role: None
[2024-05-01T16:01:37.374+0300] {subprocess.py:93} INFO - [0m13:01:37    search_path: None
[2024-05-01T16:01:37.376+0300] {subprocess.py:93} INFO - [0m13:01:37    keepalives_idle: 0
[2024-05-01T16:01:37.378+0300] {subprocess.py:93} INFO - [0m13:01:37    sslmode: None
[2024-05-01T16:01:37.381+0300] {subprocess.py:93} INFO - [0m13:01:37    sslcert: None
[2024-05-01T16:01:37.384+0300] {subprocess.py:93} INFO - [0m13:01:37    sslkey: None
[2024-05-01T16:01:37.387+0300] {subprocess.py:93} INFO - [0m13:01:37    sslrootcert: None
[2024-05-01T16:01:37.389+0300] {subprocess.py:93} INFO - [0m13:01:37    application_name: dbt
[2024-05-01T16:01:37.392+0300] {subprocess.py:93} INFO - [0m13:01:37    retries: 1
[2024-05-01T16:01:37.395+0300] {subprocess.py:93} INFO - [0m13:01:37  Registered adapter: postgres=1.7.13
[2024-05-01T16:01:38.459+0300] {subprocess.py:93} INFO - [0m13:01:38    Connection test: [[32mOK connection ok[0m]
[2024-05-01T16:01:38.460+0300] {subprocess.py:93} INFO - 
[2024-05-01T16:01:38.463+0300] {subprocess.py:93} INFO - [0m13:01:38  [31m1 check failed:[0m
[2024-05-01T16:01:38.465+0300] {subprocess.py:93} INFO - [0m13:01:38  Project loading failed for the following reason:
[2024-05-01T16:01:38.466+0300] {subprocess.py:93} INFO -  project path </tmp/airflowtmp9x7azwoz/dbt_project.yml> not found
[2024-05-01T16:01:38.466+0300] {subprocess.py:93} INFO - 
[2024-05-01T16:01:44.051+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-01T16:01:44.052+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T16:01:44.176+0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-01T16:01:44.180+0300] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_debug, execution_date=20240501T123608, start_date=20240501T125746, end_date=20240501T130144
[2024-05-01T16:01:44.506+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task dbt_debug (Bash command failed. The command returned a non-zero exit code 1.; 19399)
[2024-05-01T16:01:44.538+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T16:01:45.947+0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T16:01:46.061+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
