[2024-05-01T16:04:33.847+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T16:04:34.134+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_run manual__2024-05-01T13:04:12.949516+00:00 [queued]>
[2024-05-01T16:04:34.175+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_run manual__2024-05-01T13:04:12.949516+00:00 [queued]>
[2024-05-01T16:04:34.176+0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2024-05-01T16:04:34.507+0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_run> on 2024-05-01 13:04:12.949516+00:00
[2024-05-01T16:04:34.511+0300] {standard_task_runner.py:63} INFO - Started process 26425 to run task
[2024-05-01T16:04:34.517+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_run', 'manual__2024-05-01T13:04:12.949516+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/bash.py', '--cfg-path', '/tmp/tmpbxb2ufzw']
[2024-05-01T16:04:34.519+0300] {standard_task_runner.py:91} INFO - Job 15: Subtask dbt_run
[2024-05-01T16:04:35.608+0300] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_run manual__2024-05-01T13:04:12.949516+00:00 [running]> on host yohanes-Satellite-Pro-C50-A363
[2024-05-01T16:04:44.508+0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T13:04:12.949516+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T13:04:12.949516+00:00'
[2024-05-01T16:04:44.508+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T16:04:45.094+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T16:04:45.095+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run']
[2024-05-01T16:04:45.142+0300] {subprocess.py:86} INFO - Output:
[2024-05-01T16:06:30.842+0300] {subprocess.py:93} INFO - [0m13:06:30  Running with dbt=1.7.13
[2024-05-01T16:06:30.948+0300] {subprocess.py:93} INFO - [0m13:06:30  Encountered an error:
[2024-05-01T16:06:30.948+0300] {subprocess.py:93} INFO - Runtime Error
[2024-05-01T16:06:30.949+0300] {subprocess.py:93} INFO -   No dbt_project.yml found at expected path /tmp/airflowtmp8zcf1z44/dbt_project.yml
[2024-05-01T16:06:30.949+0300] {subprocess.py:93} INFO -   Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
[2024-05-01T16:06:30.949+0300] {subprocess.py:93} INFO - 
[2024-05-01T16:06:33.877+0300] {subprocess.py:97} INFO - Command exited with return code 2
[2024-05-01T16:06:33.878+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T16:06:33.901+0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-01T16:06:34.205+0300] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_run, execution_date=20240501T130412, start_date=20240501T130434, end_date=20240501T130634
[2024-05-01T16:06:34.347+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 26425)
[2024-05-01T16:06:34.372+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T16:06:47.612+0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T16:06:47.971+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
