[2024-05-01T16:04:33.835+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T16:04:34.132+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_run manual__2024-05-01T13:04:19.553322+00:00 [queued]>
[2024-05-01T16:04:34.175+0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_run manual__2024-05-01T13:04:19.553322+00:00 [queued]>
[2024-05-01T16:04:34.175+0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2024-05-01T16:04:34.313+0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_run> on 2024-05-01 13:04:19.553322+00:00
[2024-05-01T16:04:34.319+0300] {standard_task_runner.py:63} INFO - Started process 26408 to run task
[2024-05-01T16:04:34.340+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_run', 'manual__2024-05-01T13:04:19.553322+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/bash.py', '--cfg-path', '/tmp/tmpmrrcdbnm']
[2024-05-01T16:04:34.345+0300] {standard_task_runner.py:91} INFO - Job 14: Subtask dbt_run
[2024-05-01T16:04:35.531+0300] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_run manual__2024-05-01T13:04:19.553322+00:00 [running]> on host yohanes-Satellite-Pro-C50-A363
[2024-05-01T16:04:44.323+0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T13:04:19.553322+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T13:04:19.553322+00:00'
[2024-05-01T16:04:44.324+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T16:04:45.103+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T16:04:45.105+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run']
[2024-05-01T16:04:45.128+0300] {subprocess.py:86} INFO - Output:
[2024-05-01T16:06:30.843+0300] {subprocess.py:93} INFO - [0m13:06:30  Running with dbt=1.7.13
[2024-05-01T16:06:30.948+0300] {subprocess.py:93} INFO - [0m13:06:30  Encountered an error:
[2024-05-01T16:06:30.948+0300] {subprocess.py:93} INFO - Runtime Error
[2024-05-01T16:06:30.949+0300] {subprocess.py:93} INFO -   No dbt_project.yml found at expected path /tmp/airflowtmp_tyv2hbp/dbt_project.yml
[2024-05-01T16:06:30.949+0300] {subprocess.py:93} INFO -   Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
[2024-05-01T16:06:30.949+0300] {subprocess.py:93} INFO - 
[2024-05-01T16:06:38.731+0300] {subprocess.py:97} INFO - Command exited with return code 2
[2024-05-01T16:06:38.732+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T16:06:38.765+0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yohanes/Documents/10academy/week2_2/10ac_city_traffic_data_warehouse_week2/week2_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-01T16:06:38.771+0300] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_run, execution_date=20240501T130419, start_date=20240501T130434, end_date=20240501T130638
[2024-05-01T16:06:38.859+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 26408)
[2024-05-01T16:06:38.900+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T16:06:47.660+0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T16:06:47.993+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
